// 100개 이벤트 데이터. 숫자는 전부 rules.ts의 표준 피해/보상 단계
// (HP 5/10/15/20/30/40, 정신력 3/5/10/15/20, 은신처 5/10/15/20/30, 자원 1/2/3/5)
// 안에서만 고른다 (기획서 28, 29번 규칙).
import type { GameEvent } from './types'
import {
  c,
  contamination,
  counter,
  ev,
  flag,
  food,
  hp,
  info,
  item,
  mental,
  power,
  roll,
  routeEff,
  shelter,
  status,
  survivorHp,
  survivorJoin,
  survivorLeave,
  survivorTrust,
  trust,
  water,
} from './effects'

// ============================== DAY 1~5 : 초반 생존 ==============================
const DAY_1_5: GameEvent[] = [
  ev(
    'e001',
    1,
    5,
    '문밖의 발자국',
    '밖에 사람의 발자국이 남아 있다.',
    'danger',
    [
      roll('check', '확인한다', 70, [food(1)], '발자국을 따라가니 식량을 발견했다.', [status('injured', true)], '무언가에 걸려 넘어졌다. 부상을 입었다.'),
      c('ignore', '무시한다', [mental(2)], '신경 쓰지 않기로 했다. 마음이 조금 편해졌다.'),
      c('lock', '문을 잠근다', [shelter(5)], '문단속을 단단히 했다.'),
    ],
    { fixed: true },
  ),
  ev(
    'e002',
    1,
    5,
    '새는 수도관',
    '벽에서 물이 새고 있다.',
    'resource',
    [
      c('catch', '받는다', [water(2), shelter(-5)], '그릇에 물을 받았다. 벽은 조금 상했다.'),
      c('fix', '수리한다', [shelter(5)], '수리했다.', { item: 'toolbox' }),
      c('leave', '무시한다', [shelter(-10)], '결국 내구도가 더 상했다.'),
    ],
  ),
  ev(
    'e003',
    1,
    5,
    '약한 라디오',
    '잡음 사이로 사람 목소리가 들리는 것 같다.',
    'story',
    [
      c('listen', '주파수를 맞춰 본다', [info(10), counter('radioStory', 1)], '희미하지만 분명한 목소리였다. 정보를 얻었다.', { item: 'radio' }),
      c('noRadio', '라디오가 없다', [], '아무것도 확인하지 못했다.'),
    ],
    { fixed: true },
  ),
  ev(
    'e004',
    1,
    5,
    '통조림 하나',
    '구석에서 통조림을 발견했다.',
    'resource',
    [
      c('eat', '바로 먹는다', [hp(5)], '따뜻하진 않지만 배는 채웠다.'),
      c('store', '저장한다', [food(1)], '나중을 위해 아껴 두었다.'),
      c('drop', '버린다', [mental(2)], '괜히 홀가분했다.'),
    ],
  ),
  ev(
    'e005',
    1,
    5,
    '이상한 냄새',
    '대피소에서 타는 냄새가 은은하게 난다.',
    'danger',
    [
      c('inspect', '조사한다', [flag('electricChecked'), power(-2)], '낡은 배선 문제를 발견해 손을 봤다.'),
      c('vent', '환기한다', [mental(3)], '창을 열어 환기하니 한결 나았다.'),
      c('ignoreSmell', '무시한다', [flag('fireRisk')], '별일 아니겠거니 했다. 왠지 불안하다.'),
    ],
    { fixed: true },
  ),
  ev(
    'e006',
    1,
    5,
    '창밖의 불빛',
    '멀리서 손전등 같은 불빛이 움직인다.',
    'survival',
    [
      c('signal', '신호를 보낸다', [flag('signaledOutside')], '손전등을 두 번 깜빡였다. 저쪽에서도 반응이 있었다.'),
      c('ignoreLight', '무시한다', [], '아무 일도 일어나지 않았다.'),
      c('watch', '망원경으로 관찰한다', [info(5)], '누군가 이동하는 모습을 확인했다.', { item: 'binoculars' }),
    ],
  ),
  ev(
    'e007',
    1,
    5,
    '잠을 잘 수 없다',
    '밤새 이상한 소리가 들려 뒤척인다.',
    'survival',
    [
      c('watchNight', '경계한다', [mental(-2)], '뜬눈으로 밤을 지새웠다.'),
      roll('sleep', '그냥 잔다', 80, [hp(8)], '푹 잤다.', [hp(-10), shelter(-5)], '자는 사이 무언가 대피소를 건드렸다.'),
    ],
  ),
  ev(
    'e008',
    1,
    5,
    '작은 상처',
    '탐색 중 손을 다쳤다.',
    'survival',
    [
      c('treatNow', '즉시 붕대를 감는다', [], '상처를 바로 처치했다.', { item: 'bandage' }),
      c('leaveIt', '그냥 둔다', [status('injured', true)], '일단 부상 상태가 되었다.'),
    ],
  ),
  ev(
    'e009',
    1,
    5,
    '오래된 신문',
    '오래된 신문에서 재난 발생일에 대한 기사를 발견했다.',
    'story',
    [c('read', '읽어 본다', [info(5)], '재난 초기의 정황을 알게 되었다.')],
  ),
  ev(
    'e010',
    1,
    5,
    '비',
    '밖에 비가 내린다.',
    'resource',
    [
      c('filterRain', '정수해서 받는다', [water(3)], '깨끗한 물을 받았다.', { item: 'filter' }),
      c('rawRain', '그냥 받는다', [water(3), contamination(5)], '일단 받았지만 물이 조금 탁하다.'),
    ],
  ),
  ev(
    'e011',
    1,
    5,
    '쥐',
    '대피소 안에 쥐가 나타났다.',
    'survival',
    [
      c('catchRat', '잡는다', [food(1)], '식량으로 삼았다.', { item: 'knife' }),
      c('shooRat', '쫓아낸다', [mental(1)], '내보냈다.'),
      c('leaveRat', '방치한다', [food(-1)], '식량을 축냈다.'),
    ],
  ),
  ev(
    'e012',
    1,
    5,
    '이상한 소리',
    '벽 안쪽에서 두드리는 소리가 난다.',
    'rare',
    [
      c('breakWall', '벽을 뜯는다', [item('battery', 1), flag('wallOpened')], '숨겨진 배터리를 찾았다.', { item: 'toolbox' }),
      c('ignoreWall', '무시한다', [flag('wallNoise')], '신경 쓰지 않기로 했다.'),
    ],
  ),
  ev('e013', 1, 5, '낡은 배터리', '구석에서 배터리를 발견했다.', 'resource', [c('take013', '챙긴다', [item('battery', 2)], '배터리 2개를 얻었다.')]),
  ev(
    'e014',
    1,
    5,
    '식량 냄새',
    '어디선가 통조림 냄새가 난다.',
    'resource',
    [c('find014', '따라가 본다', [food(1)], '냄새를 따라가니 통조림이 있었다.')],
  ),
  ev(
    'e015',
    1,
    5,
    '첫 번째 악몽',
    '재난 직전의 기억을 꿈으로 꾸었다.',
    'story',
    [c('dream015', '식은땀을 닦는다', [mental(-5), info(3)], '흐릿했던 기억의 조각이 떠올랐다.')],
  ),
  ev(
    'e016',
    1,
    5,
    '정체불명의 노크',
    '문을 세 번 두드리는 소리가 났다.',
    'danger',
    [
      c('open016', '연다', [flag('visitorMet')], '문을 여니 아무도 없었다. 대신 발자국만 남아 있었다.'),
      c('answer016', '대답만 한다', [trust(2)], '대답하니 조용해졌다.'),
      c('ignore016', '무시한다', [mental(-3)], '끝내 대답하지 않았다. 마음이 무겁다.'),
    ],
    { fixed: true },
  ),
  ev(
    'e017',
    1,
    5,
    '깨진 창문',
    '창문이 깨졌다.',
    'danger',
    [
      c('fixWindow', '판자로 막는다', [shelter(5)], '판자로 막아 보강했다.', { item: 'toolbox' }),
      c('leaveWindow', '방치한다', [shelter(-10)], '찬 바람이 계속 들어온다.'),
    ],
  ),
  ev(
    'e018',
    1,
    5,
    '식수 확인',
    '보관 중인 물을 확인한다.',
    'resource',
    [
      c('cleanWater', '정화한다', [contamination(-10)], '정수 필터로 오염을 제거했다.', { item: 'filter' }),
      c('discardWater', '의심스러운 만큼 버린다', [water(-1)], '아까웠지만 버렸다.'),
    ],
  ),
  ev(
    'e019',
    1,
    5,
    '오래된 사진',
    '누군가의 가족사진을 발견했다.',
    'story',
    [c('keepPhoto', '챙긴다', [info(2), mental(3)], '낯선 가족의 웃는 얼굴이 위안이 됐다.')],
  ),
  ev(
    'e020',
    1,
    5,
    '비상식량',
    '숨겨진 식량 창고를 발견했다.',
    'rare',
    [c('stockpile', '전부 챙긴다', [food(3)], '뜻밖의 큰 수확이었다.')],
    { fixed: true },
  ),
]

// ============================== DAY 6~10 : 외부와의 접촉 ==============================
const DAY_6_10: GameEvent[] = [
  ev(
    'e021',
    6,
    10,
    '구조 요청',
    '무전기에서 구조 요청 신호가 잡힌다.',
    'story',
    [c('receive021', '수신한다', [info(10), counter('radioStory', 1)], '좌표 일부를 받아 적었다.', { item: 'walkie' })],
    { fixed: true, requires: (s) => (s.inventory.walkie ?? 0) > 0 },
  ),
  ev(
    'e022',
    6,
    10,
    '생존자',
    '문밖에서 여성이 도움을 요청한다.',
    'story',
    [
      c('welcome022', '들인다', [survivorJoin(), trust(10)], '떨고 있던 그녀를 안으로 들였다.'),
      c('refuse022', '거절한다', [mental(-5)], '문을 열지 않았다. 마음이 편치 않다.'),
      c('ask022', '질문한다', [info(5)], '문틈으로 몇 가지를 물었다.'),
    ],
    { fixed: true },
  ),
  ev(
    'e023',
    6,
    10,
    '아이의 목소리',
    '밖에서 아이 울음소리가 들린다.',
    'danger',
    [
      roll('goOut023', '나간다', 60, [survivorJoin('civilian')], '길 잃은 아이를 데려왔다.', [hp(-15), status('injured', true)], '함정이었다. 다쳤다.'),
      c('wait023', '기다린다', [flag('childWaiting')], '일단 기다려 보기로 했다.'),
      c('ignore023', '무시한다', [mental(-8)], '외면했다. 오래도록 마음에 남을 것 같다.'),
    ],
  ),
  ev(
    'e024',
    6,
    10,
    '편의점 발견',
    '가까운 편의점이 아직 무너지지 않았다.',
    'resource',
    [roll('explore024', '탐색한다', 75, [food(2), water(2)], '식량과 물을 챙겼다.', [status('injured', true)], '진열대가 무너지며 다쳤다.')],
  ),
  ev(
    'e025',
    6,
    10,
    '병원',
    '병원 건물이 보인다.',
    'resource',
    [roll('explore025', '탐색한다', 60, [item('medicine', 2), item('bandage', 2)], '의약품을 확보했다.', [status('injured', true)], '유리 파편에 다쳤다.')],
  ),
  ev(
    'e026',
    6,
    10,
    '이상한 감염',
    '생존자 한 명에게 열이 오른다.',
    'danger',
    [
      c('cure026', '치료한다', [survivorHp(20)], '의약품으로 열을 내렸다.', { item: 'medicine' }),
      c('noCure026', '지켜본다', [survivorHp(-20)], '상태가 나빠졌다.'),
    ],
    { requires: (s) => s.survivors.some((sv) => sv.alive) },
  ),
  ev(
    'e027',
    6,
    10,
    '약탈자',
    '무기를 든 사람들이 밖에 나타났다.',
    'danger',
    [
      c('hide027', '숨는다', [mental(-5)], '숨죽인 채 지나가길 기다렸다.'),
      c('negotiate027', '협상한다', [food(-2)], '식량을 나눠 주고 돌려보냈다.'),
      roll('fight027', '맞선다', 55, [shelter(-5)], '몰아냈다. 대피소가 약간 상했다.', [hp(-20), shelter(-15)], '크게 다치고 대피소도 부서졌다.', { item: 'axe' }),
    ],
  ),
  ev('e028', 6, 10, '발전기 소리', '밖에서 발전기 소리가 들린다.', 'story', [c('note028', '방향을 기록한다', [info(5)], '소리가 나는 방향을 지도에 표시했다.')]),
  ev(
    'e029',
    6,
    10,
    '정전',
    '갑자기 전력이 나갔다.',
    'danger',
    [
      c('genFix029', '발전기로 버틴다', [power(5)], '발전기 덕에 큰 피해는 없었다.', { item: 'generator' }),
      c('darkNight029', '어둠 속에서 버틴다', [power(-10), mental(-3)], '불안한 밤을 보냈다.'),
    ],
  ),
  ev(
    'e030',
    6,
    10,
    '폭우',
    '밤새 비가 거세게 내린다.',
    'danger',
    [
      c('filterRain030', '정수 필터로 받는다', [water(3), shelter(-5)], '물은 확보했지만 지붕이 약간 상했다.', { item: 'filter' }),
      c('rawRain030', '그냥 버틴다', [shelter(-15)], '대피소 내구도가 크게 상했다.'),
    ],
  ),
  ev(
    'e031',
    6,
    10,
    '라디오 방송',
    '"북쪽으로 이동하지 마십시오." 라디오에서 반복되는 경고가 흘러나온다.',
    'story',
    [c('heed031', '기록해 둔다', [info(10), counter('radioStory', 1)], '불길한 경고를 수첩에 옮겨 적었다.', { item: 'radio' })],
    { requires: (s) => (s.inventory.radio ?? 0) > 0 },
  ),
  ev(
    'e032',
    6,
    10,
    '거짓말',
    '생존자가 무언가를 숨기는 눈치다.',
    'story',
    [
      c('press032', '추궁한다', [trust(-10)], '분위기가 싸늘해졌다.'),
      c('watch032', '관찰만 한다', [info(5)], '단서를 조금 모았다.'),
      c('trustEvent032', '믿기로 한다', [trust(10)], '캐묻지 않기로 했다.'),
    ],
    { requires: (s) => s.survivors.some((sv) => sv.alive) },
  ),
  ev(
    'e033',
    6,
    10,
    '비밀 식량',
    '생존자가 식량을 몰래 숨겨 뒀던 걸 발견했다.',
    'story',
    [c('confront033', '알게 됐다', [food(2), trust(-15)], '식량은 되찾았지만 신뢰는 잃었다.')],
    { requires: (s) => s.survivors.some((sv) => sv.alive) },
  ),
  ev(
    'e034',
    6,
    10,
    '손전등 신호',
    '밖에서 불빛이 세 번 깜빡인다.',
    'story',
    [
      c('decode034', '암호를 확인한다', [info(5), flag('signalDecoded')], '규칙적인 패턴이었다. 신호처럼 보인다.', { item: 'binoculars' }),
      c('noBino034', '망원경이 없다', [], '너무 멀어 확인할 수 없었다.'),
    ],
  ),
  ev(
    'e035',
    6,
    10,
    '지도 발견',
    '지도에 표시되지 않은 장소가 있다.',
    'rare',
    [c('markMap035', '표시해 둔다', [flag('hiddenSpotKnown'), info(5)], '지도에 없는 장소를 알게 됐다.', { item: 'map' })],
    { requires: (s) => (s.inventory.map ?? 0) > 0 },
  ),
  ev(
    'e036',
    6,
    10,
    '환풍구',
    '환풍구를 통해 외부 공기가 들어온다.',
    'danger',
    [
      c('mask036', '마스크를 쓴다', [], '안전하게 확인했다.', { item: 'mask' }),
      roll('noMask036', '그냥 확인한다', 50, [], '별일 없었다.', [contamination(10)], '탁한 공기를 들이마셨다.'),
    ],
  ),
  ev(
    'e037',
    6,
    10,
    '라디오 잡음',
    '특정 주파수에서 이상한 숫자가 반복해서 들린다.',
    'story',
    [c('numbers037', '숫자를 받아 적는다', [info(10), counter('radioStory', 1)], '의미를 알 수 없는 숫자열을 기록했다.', { item: 'radio' })],
    { requires: (s) => (s.inventory.radio ?? 0) > 0 },
  ),
  ev(
    'e038',
    6,
    10,
    '낙서',
    '벽에 누군가 급하게 남긴 글씨가 있다. "30일째에는 문을 열지 마."',
    'story',
    [c('read038', '읽는다', [flag('doorWarning'), mental(-3)], '누가 남겼을지 모를 경고가 마음에 박혔다.')],
    { fixed: true },
  ),
  ev(
    'e039',
    6,
    10,
    '실종',
    '생존자 한 명이 사라졌다.',
    'danger',
    [c('missing039', '흔적을 찾는다', [mental(-10), survivorLeave()], '끝내 찾지 못했다.')],
    { requires: (s) => s.survivors.some((sv) => sv.alive) },
  ),
  ev(
    'e040',
    6,
    10,
    '밤의 방문자',
    '문밖에 누군가 조용히 서 있다.',
    'danger',
    [
      c('openDoor040', '문을 연다', [hp(-10)], '경계할 새도 없이 밀쳐졌다.'),
      c('watch040', '망원경으로 관찰한다', [info(5)], '누구인지 확인했다.', { item: 'binoculars' }),
      c('ignore040', '무시한다', [], '기척이 사라졌다.'),
    ],
  ),
]

// ============================== DAY 11~15 : 위기 ==============================
const DAY_11_15: GameEvent[] = [
  ev('e041', 11, 15, '물 부족', '비축된 물이 눈에 띄게 줄었다.', 'resource', [c('note041', '아껴 쓰기로 한다', [water(-1)], '오늘은 평소보다 아껴 마셨다.')]),
  ev(
    'e042',
    11,
    15,
    '식량 배급',
    '식량이 부족해 나눠야 할 상황이다.',
    'resource',
    [
      c('share042', '나눠 먹는다', [food(-2), mental(5, )], '다 함께 나눠 먹었다. 분위기가 한결 나아졌다.'),
      c('keep042', '혼자 먹는다', [trust(-10)], '눈치가 보였다.'),
    ],
    { requires: (s) => s.survivors.some((sv) => sv.alive) },
  ),
  ev(
    'e043',
    11,
    15,
    '부상 악화',
    '치료하지 않은 상처가 욱신거린다.',
    'danger',
    [c('worse043', '버틴다', [hp(-10)], '상처가 덧났다.')],
    { requires: (s) => s.statusEffects.injured },
  ),
  ev(
    'e044',
    11,
    15,
    '대피소 균열',
    '벽에 큰 균열이 생겼다.',
    'danger',
    [
      c('fix044', '공구상자로 보강한다', [shelter(-10)], '피해를 최소화했다.', { item: 'toolbox' }),
      c('nofix044', '어쩔 도리가 없다', [shelter(-20)], '균열이 더 커졌다.'),
    ],
  ),
  ev(
    'e045',
    11,
    15,
    '화재',
    '한쪽 구석에서 불씨가 일었다.',
    'danger',
    [
      c('extinguish045', '소화한다', [shelter(-5)], '빠르게 진화했다.', { item: 'matches' }),
      roll('escape045', '탈출한다', 60, [], '무사히 피했다.', [survivorLeave()], '혼란 속에 한 명을 놓쳤다.', { survivor: true }),
      c('leaveFire045', '방치한다', [shelter(-30)], '피해가 크게 번졌다.'),
    ],
  ),
  ev(
    'e046',
    11,
    15,
    '병원 약품',
    '병원을 다시 찾아가 본다.',
    'resource',
    [roll('reexplore046', '탐색한다', 55, [item('medicine', 3)], '의약품을 넉넉히 확보했다.', [status('injured', true)], '무너진 잔해에 다쳤다.')],
  ),
  ev(
    'e047',
    11,
    15,
    '이상한 환자',
    '병원에서 홀로 남은 환자를 발견했다.',
    'rare',
    [
      c('bring047', '데려온다', [survivorJoin('doctor')], '알고 보니 이 병원의 의사였다.'),
      c('leave047', '두고 온다', [mental(-3)], '혼자 남겨 두고 왔다.'),
    ],
  ),
  ev(
    'e048',
    11,
    15,
    '군용 차량',
    '길가에 버려진 군용 차량이 있다.',
    'story',
    [roll('search048', '수색한다', 55, [item('battery', 1), info(5)], '배터리와 기록 일부를 확보했다.', [status('injured', true)], '날카로운 파편에 다쳤다.')],
    { fixed: true },
  ),
  ev(
    'e049',
    11,
    15,
    '군용 기록',
    '차량 안에서 기록물을 발견했다.',
    'story',
    [c('readRecord049', '읽는다', [info(15), flag('militaryRecord')], '재난 초기 군의 대응 기록이었다.')],
    { requires: (s) => s.firedEventIds.includes('e048'), fixed: true },
  ),
  ev(
    'e050',
    11,
    15,
    '검은 비',
    '검은빛을 띠는 비가 내린다.',
    'danger',
    [
      c('protect050', '마스크와 필터로 대비한다', [contamination(5)], '피해를 줄였다.', { item: 'mask' }),
      c('exposed050', '그대로 맞는다', [contamination(20)], '오염 수치가 크게 올랐다.'),
    ],
  ),
  ev(
    'e051',
    11,
    15,
    '오염',
    '몸 상태가 이상하다.',
    'danger',
    [c('checkContam051', '상태를 확인한다', [], '오염 수치에 따라 몸이 반응하고 있다.')],
    { requires: (s) => s.stats.contamination >= 50 },
  ),
  ev(
    'e052',
    11,
    15,
    "생존자의 고백",
    '생존자가 재난에 대해 알고 있는 것이 있다고 털어놓는다.',
    'story',
    [c('confess052', '듣는다', [info(15), trust(10)], '전에 어디선가 일하고 있었다는 이야기를 들었다.')],
    { requires: (s) => s.survivors.some((sv) => sv.alive), fixed: true },
  ),
  ev(
    'e053',
    11,
    15,
    '거짓 구조대',
    '구조대를 자처하는 이들이 방송을 보낸다.',
    'story',
    [
      c('seeThrough053', '거짓임을 알아챈다', [info(5)], '앞뒤가 맞지 않는 부분을 짚어냈다.', { infoMin: 40 }),
      c('believe053', '믿어 본다', [mental(-5)], '기대했지만 아무도 오지 않았다.'),
    ],
  ),
  ev(
    'e054',
    11,
    15,
    '식량 도둑',
    '보관해 둔 식량이 사라졌다.',
    'danger',
    [c('investigate054', '조사한다', [food(-2), trust(-5)], '범인은 끝내 밝히지 못했다.')],
  ),
  ev(
    'e055',
    11,
    15,
    '비밀 통로',
    '대피소 벽 뒤에서 좁은 통로를 발견했다.',
    'rare',
    [c('open055', '통로를 연다', [flag('secretPassage'), info(5)], '어디로 이어지는지 모를 통로였다.')],
  ),
  ev(
    'e056',
    11,
    15,
    '오래된 기록',
    '재난 이전의 연구 기록을 발견했다.',
    'story',
    [c('read056', '읽는다', [info(15)], '재난 발생 이전의 이상한 연구 기록이었다.')],
  ),
  ev(
    'e057',
    11,
    15,
    '이상한 전파',
    '라디오에서 사람 목소리가 아닌 소리가 흘러나온다.',
    'danger',
    [c('listen057', '끝까지 듣는다', [mental(-10)], '설명할 수 없는 불쾌한 소리였다.', { item: 'radio' })],
    { requires: (s) => (s.inventory.radio ?? 0) > 0 },
  ),
  ev(
    'e058',
    11,
    15,
    '구조 헬기',
    '하늘에서 헬기 소리가 들린다.',
    'danger',
    [
      c('signal058', '신호를 보낸다', [flag('helicopterSignaled')], '있는 힘껏 신호를 보냈지만 헬기는 그대로 지나갔다.'),
      c('hide058', '숨는다', [], '안전하게 지나가길 기다렸다.'),
    ],
  ),
  ev(
    'e059',
    11,
    15,
    '식수 정화',
    '오염된 물을 정화할 수 있다.',
    'resource',
    [c('purify059', '정수한다', [contamination(-20), water(1)], '깨끗한 물을 조금 더 확보했다.', { item: 'filter' })],
    { requires: (s) => (s.inventory.filter ?? 0) > 0 },
  ),
  ev(
    'e060',
    15,
    15,
    '15일째',
    '"15일째. 절반을 버텼다." 라디오에서 낮은 목소리가 흘러나온다. "구조는 오지 않는다."',
    'story',
    [c('accept060', '받아들인다', [info(20), mental(-5)], '무거운 확신이 마음에 내려앉았다.')],
    { fixed: true },
  ),
]

// ============================== DAY 16~20 : 진실에 접근 ==============================
const DAY_16_20: GameEvent[] = [
  ev(
    'e061',
    16,
    20,
    '북쪽 신호',
    '북쪽에서 구조 신호가 잡힌다.',
    'story',
    [c('north061', '방향을 기록한다', [routeEff('north'), info(5)], '북쪽 루트가 지도에 표시됐다.')],
  ),
  ev(
    'e062',
    16,
    20,
    '남쪽 신호',
    '남쪽에서 식량 관련 신호가 잡힌다.',
    'story',
    [c('south062', '방향을 기록한다', [routeEff('south'), info(5)], '남쪽 루트가 지도에 표시됐다.')],
  ),
  ev(
    'e063',
    16,
    20,
    '두 신호',
    '북쪽과 남쪽, 두 신호가 동시에 들어온다. 하나를 선택해야 한다.',
    'story',
    [
      c('chooseNorth063', '북쪽을 택한다', [routeEff('north'), flag('routeChosen')], '북쪽 공동체 쪽으로 방향을 정했다.'),
      c('chooseSouth063', '남쪽을 택한다', [routeEff('south'), flag('routeChosen')], '남쪽 군사 시설 쪽으로 방향을 정했다.'),
    ],
  ),
  ev(
    'e064',
    16,
    20,
    '북쪽 공동체',
    '북쪽 루트를 따라가니 생존자 집단이 있었다는 흔적이 있다.',
    'story',
    [c('found064', '흔적을 조사한다', [info(10), trust(5)], '사람이 살았던 흔적이 또렷했다.')],
    { requires: (s) => s.route === 'north' },
  ),
  ev(
    'e065',
    16,
    20,
    '남쪽 기지',
    '남쪽 루트를 따라가니 군사 시설 흔적이 있다.',
    'story',
    [c('found065', '흔적을 조사한다', [info(10), flag('militaryRecord')], '버려진 군사 시설이었다.')],
    { requires: (s) => s.route === 'south' },
  ),
  ev(
    'e066',
    16,
    20,
    '배신',
    '신뢰가 낮았던 생존자가 자원을 훔쳐 사라졌다.',
    'danger',
    [c('betrayed066', '피해를 확인한다', [food(-3), water(-3), survivorLeave()], '가장 믿지 못했던 사람이었다.')],
    { requires: (s) => s.survivors.some((sv) => sv.alive && sv.trust < 40) },
  ),
  ev(
    'e067',
    16,
    20,
    '협력',
    '신뢰가 높은 생존자가 자신의 비상식량을 나눠 준다.',
    'story',
    [c('helped067', '고맙게 받는다', [food(2), mental(5)], '뜻밖의 온기였다.')],
    { requires: (s) => s.survivors.some((sv) => sv.alive && sv.trust >= 60) },
  ),
  ev(
    'e068',
    16,
    20,
    'CCTV',
    '발전기로 전력을 넣으니 오래된 CCTV 저장 장치가 켜진다.',
    'story',
    [c('watchCctv068', '영상을 확인한다', [info(20), power(-5)], '재난 당일의 장면이 담겨 있었다.', { item: 'generator' })],
    { fixed: true, requires: (s) => (s.inventory.generator ?? 0) > 0 },
  ),
  ev(
    'e069',
    16,
    20,
    '연구원 기록',
    '지하 연구시설에 관한 기록을 발견했다.',
    'story',
    [c('read069', '읽는다', [info(10), flag('researchRecord')], '시설의 존재를 확신하게 됐다.')],
  ),
  ev(
    'e070',
    16,
    20,
    '이름',
    '기록에 등장하는 연구원의 이름이, 예전에 만났던 생존자의 이름과 같다.',
    'story',
    [c('realize070', '기록을 다시 확인한다', [info(10)], '우연이라기엔 너무 정확히 일치했다.')],
    { requires: (s) => s.flags.researchRecord === true },
  ),
  ev(
    'e071',
    16,
    20,
    '실험실',
    '지도에 없던 지하 연구시설 입구를 찾았다.',
    'danger',
    [
      roll(
        'exploreLab071',
        '진입한다',
        25,
        [flag('labExplored'), info(15)],
        '깊숙한 곳까지 들어가 무언가를 확인했다.',
        [hp(-20), status('injured', true)],
        '무너진 통로에 크게 다쳤다.',
      ),
    ],
  ),
  ev(
    'e072',
    16,
    20,
    '이상한 약',
    '연구실에서 정체 모를 약을 발견했다.',
    'rare',
    [roll('takeDrug072', '복용한다', 80, [hp(30)], '몸 상태가 눈에 띄게 좋아졌다.', [mental(-20)], '알 수 없는 부작용에 시달렸다.')],
    { requires: (s) => s.flags.labExplored === true },
  ),
  ev(
    'e073',
    16,
    20,
    '냉동실',
    '연구시설 안쪽, 냉동 보관된 무언가를 발견했다.',
    'story',
    [c('findFreezer073', '확인한다', [flag('freezerSeen'), mental(-10)], '무엇인지는 알 수 없지만, 보지 말았어야 했다는 생각이 들었다.')],
    { requires: (s) => s.flags.labExplored === true, fixed: true },
  ),
  ev(
    'e074',
    16,
    20,
    '검은 상자',
    '군용 블랙박스를 발견했다.',
    'story',
    [c('openBox074', '연다', [info(20), flag('blackBox')], '재난 직전의 영상 기록이 담겨 있었다.')],
    { requires: (s) => s.flags.militaryRecord === true, fixed: true },
  ),
  ev(
    'e075',
    16,
    20,
    '마지막 명령',
    '블랙박스 속 마지막 명령이 재생된다. "모든 대피소를 폐쇄하라."',
    'story',
    [c('hearOrder075', '끝까지 듣는다', [info(15), mental(-5)], '누구의 명령이었는지는 나오지 않았다.')],
    { requires: (s) => s.flags.blackBox === true },
  ),
  ev(
    'e076',
    16,
    20,
    '탈출 차량',
    '연료가 조금 남은 차량을 발견했다.',
    'story',
    [c('readyVehicle076', '정비해 둔다', [flag('escapeVehicleReady')], '언제든 떠날 수 있게 준비해 두었다.', { item: 'generator' })],
    { requires: (s) => (s.inventory.generator ?? 0) > 0 },
  ),
  ev(
    'e077',
    16,
    20,
    '동료의 결정',
    '생존자 한 명이 대피소를 떠나겠다고 말한다.',
    'story',
    [
      c('letGo077', '보내준다', [survivorLeave(), trust(5)], '뜻을 존중하기로 했다.'),
      c('keep077', '붙잡는다', [survivorTrust(10)], '설득 끝에 남기로 했다.'),
    ],
    { requires: (s) => s.survivors.some((sv) => sv.alive) },
  ),
  ev(
    'e078',
    16,
    20,
    '밤의 습격',
    '약탈자들이 대피소를 습격한다.',
    'danger',
    [
      c('guardedFight078', '맞서 싸운다', [shelter(-10)], '경계 태세 덕에 피해를 줄였다.', { item: 'axe' }),
      roll('fight078', '맞서 싸운다', 50, [shelter(-15)], '겨우 몰아냈다.', [hp(-20), shelter(-30)], '큰 피해를 입었다.'),
    ],
  ),
  ev(
    'e079',
    16,
    20,
    '무전기의 좌표',
    '무전기에서 알 수 없는 좌표가 반복해서 들려온다.',
    'story',
    [c('recordCoord079', '좌표를 기록한다', [flag('finalCoordKnown'), info(10)], '최종 목적지로 보이는 좌표를 얻었다.', { item: 'walkie' })],
    { fixed: true, requires: (s) => (s.inventory.walkie ?? 0) > 0 },
  ),
  ev(
    'e080',
    20,
    20,
    '20일째',
    '"20일째." 정보가 충분하다면 다음 문장이 이어진다 — "재난은 아직 끝나지 않았다."',
    'story',
    [c('milestone080', '되새긴다', [mental(-3)], '남은 열흘이 유독 길게 느껴졌다.')],
    { fixed: true },
  ),
]

// ============================== DAY 21~25 : 최종장 ==============================
const DAY_21_25: GameEvent[] = [
  ev('e081', 21, 25, '대규모 폭풍', '역대급 폭풍이 대피소를 덮친다.', 'danger', [c('storm081', '버틴다', [shelter(-20, )], '지붕 일부가 뜯겨 나갔다.')]),
  ev(
    'e082',
    21,
    25,
    '물 오염',
    '보관해 둔 물의 절반가량이 오염됐다.',
    'danger',
    [
      c('filterSafe082', '필터로 막아 냈다', [], '정수 필터 덕분에 무사했다.', { item: 'filter' }),
      c('loseWater082', '피해를 본다', [water(-2), contamination(10)], '아까운 물을 버려야 했다.'),
    ],
  ),
  ev(
    'e083',
    21,
    25,
    '생존자 감염',
    '생존자 한 명이 감염 증세를 보인다.',
    'danger',
    [
      c('cure083', '의약품으로 치료한다', [status('infected', false)], '고비를 넘겼다.', { item: 'medicine' }),
      c('noMed083', '지켜볼 수밖에 없다', [survivorHp(-20), status('infected', true)], '상태가 급격히 나빠졌다.'),
    ],
    { requires: (s) => s.survivors.some((sv) => sv.alive) },
  ),
  ev(
    'e084',
    21,
    25,
    '대피소 습격',
    '이제까지와는 다른, 조직적인 습격이다.',
    'danger',
    [
      c('weaponFight084', '무장하고 맞선다', [hp(-10), shelter(-15)], '무기 덕에 피해를 줄였다.', { item: 'axe' }),
      roll('bareFight084', '맨몸으로 맞선다', 40, [shelter(-20)], '가까스로 버텼다.', [hp(-30), shelter(-30)], '심각한 피해를 입었다.'),
    ],
  ),
  ev('e085', 21, 25, '식량 창고', '대량의 식량이 남아 있는 창고를 발견했다.', 'resource', [roll('bigFood085', '탐색한다', 55, [food(5)], '많은 식량을 확보했다.', [status('injured', true)], '무너진 선반에 다쳤다.')]),
  ev(
    'e086',
    21,
    25,
    '마지막 구조 신호',
    '구조 신호가 마지막으로 잡힌다.',
    'story',
    [c('finalSignal086', '위치를 확인한다', [flag('finalLocationKnown'), info(10)], '최종 지역의 위치가 드러났다.')],
    { fixed: true },
  ),
  ev(
    'e087',
    21,
    25,
    '탈출 준비',
    '탈출에 필요한 조건을 점검한다.',
    'story',
    [c('checkPrep087', '점검한다', [], '지금까지 모은 것들을 다시 확인했다.')],
  ),
  ev(
    'e088',
    21,
    25,
    '동료의 희생',
    '동료 한 명이 플레이어를 위해 이곳에 남겠다고 한다.',
    'story',
    [
      c('acceptSacrifice088', '뜻을 받아들인다', [survivorLeave(), flag('survivorSacrificed'), mental(-10)], '끝내 말리지 못했다.'),
      c('refuseSacrifice088', '함께 가자고 붙잡는다', [survivorTrust(15), mental(5)], '함께 가기로 했다.'),
    ],
    { requires: (s) => s.survivors.some((sv) => sv.alive) },
  ),
  ev(
    'e089',
    21,
    25,
    '진실의 문',
    '지금까지 모은 정보가 하나로 이어지기 시작한다.',
    'story',
    [c('openTruth089', '끝까지 파고든다', [flag('truthDoor'), info(5)], '재난의 전모에 조금 더 가까워졌다.')],
    { requires: (s) => s.stats.info >= 70, fixed: true },
  ),
  ev(
    'e090',
    25,
    25,
    '25일째',
    '"5일 남았다." 이 순간부터 모든 위험이 조금 더 날카로워진다.',
    'story',
    [c('milestone090', '각오를 다진다', [mental(-3)], '마지막 구간이 시작됐다.')],
    { fixed: true },
  ),
]

// ============================== DAY 26~29 : 최후 ==============================
const DAY_26_29: GameEvent[] = [
  ev(
    'e091',
    26,
    29,
    '마지막 식량',
    '식량이 거의 바닥났다. 누구에게 먼저 먹일지 정해야 한다.',
    'danger',
    [
      c('feedSelf091', '자신이 먹는다', [hp(5)], '스스로를 먼저 챙겼다.'),
      c('feedOthers091', '동료에게 먼저 먹인다', [survivorTrust(10), hp(-5)], '자신의 몫을 나눠 주었다.', { survivor: true }),
    ],
  ),
  ev(
    'e092',
    26,
    29,
    '마지막 물',
    '물이 거의 바닥났다.',
    'danger',
    [
      c('drinkSelf092', '본인이 마신다', [hp(5)], '갈증을 먼저 해결했다.'),
      c('saveWater092', '저장해 둔다', [water(1)], '아껴서 나눠 쓰기로 했다.'),
    ],
  ),
  ev(
    'e093',
    26,
    29,
    '최후의 습격',
    '지금까지 중 가장 큰 규모의 습격이다.',
    'danger',
    [c('lastRaid093', '전력으로 방어한다', [shelter(-40)], '가까스로 버텼지만 대피소가 크게 상했다.')],
  ),
  ev(
    'e094',
    26,
    29,
    '마지막 탐색',
    '이 근방에서의 마지막 탐색 기회다.',
    'rare',
    [roll('finalExplore094', '나선다', 50, [item('medicine', 1), info(10)], '중요한 물건을 손에 넣었다.', [status('injured', true)], '무리한 탐색에 다쳤다.')],
  ),
  ev(
    'e095',
    26,
    29,
    '탈출 경로',
    '지도와 정황을 종합하니 탈출 경로가 보인다.',
    'story',
    [c('routeReady095', '경로를 확정한다', [flag('escapeRouteReady')], '지도 위에 경로를 그렸다.')],
    { requires: (s) => (s.inventory.map ?? 0) > 0 && s.flags.finalLocationKnown === true },
  ),
  ev(
    'e096',
    29,
    29,
    '마지막 밤',
    '아무 일도 일어나지 않는다. 대신 지금까지의 선택들이 머릿속을 스친다. "내일이면 30일째다."',
    'story',
    [c('reflect096', '지난 시간을 돌아본다', [mental(5)], '여기까지 왔다는 사실이 새삼스럽다.')],
    { fixed: true },
  ),
  ev(
    'e097',
    26,
    29,
    '이상한 방송',
    '라디오에서 낯선 목소리가 흘러나온다. 자신의 이름을 부르는 것 같다.',
    'story',
    [c('hearName097', '귀를 기울인다', [flag('finalBroadcast'), mental(-5)], '분명히 이름을 부르고 있었다.', { item: 'radio' })],
    { fixed: true, requires: (s) => (s.inventory.radio ?? 0) > 0 },
  ),
  ev(
    'e098',
    28,
    29,
    '문밖의 사람',
    '30일째를 앞두고 누군가 문밖에서 조용히 말한다. "이제 끝났습니다."',
    'danger',
    [
      c('open098', '문을 연다', [flag('doorOpenedEarly'), hp(-15)], '문을 여는 순간 무언가 잘못됐다는 걸 깨달았다.'),
      c('notOpen098', '문을 열지 않는다', [flag('doorHeld'), mental(-3)], '낙서의 경고를 떠올리며 버텼다.'),
    ],
    { fixed: true },
  ),
  ev(
    'e099',
    26,
    29,
    '마지막 기억',
    '모아 온 정보와 기록들이 하나의 장면으로 이어진다.',
    'story',
    [c('remember099', '기억을 마주한다', [flag('finalMemory'), info(5)], '재난 발생 직전, 스스로도 잊고 있던 순간이 떠올랐다.')],
    { requires: (s) => s.flags.truthDoor === true || s.flags.blackBox === true, fixed: true },
  ),
]

export const ALL_EVENTS: GameEvent[] = [...DAY_1_5, ...DAY_6_10, ...DAY_11_15, ...DAY_16_20, ...DAY_21_25, ...DAY_26_29]

export const EVENT_MAP: Record<string, GameEvent> = Object.fromEntries(ALL_EVENTS.map((e) => [e.id, e]))
