// 100개 이벤트 데이터. 숫자는 전부 rules.ts의 표준 피해/보상 단계
// (HP 5/10/15/20/30/40, 정신력 3/5/10/15/20, 은신처 5/10/15/20/30, 자원 1/2/3/5)
// 안에서만 고른다 (기획서 28, 29번 규칙).
import type { GameEvent } from './types'
import {
  c,
  contamination,
  counter,
  ev,
  flag,
  food,
  hp,
  hunger,
  info,
  item,
  mental,
  power,
  roll,
  routeEff,
  shelter,
  status,
  survivorHp,
  survivorJoin,
  survivorLeave,
  survivorTrust,
  thirst,
  trust,
  water,
} from './effects'

// 30일을 넘겨도 게임이 계속되는 "며칠까지 버티는지"형 엔드리스 모드용 상한.
// 아래 REPEATABLE 이벤트들은 이 날짜까지 계속 다시 뽑힐 수 있다.
const ENDLESS_DAY_MAX = 9999

// ============================== DAY 1~5 : 초반 생존 ==============================
const DAY_1_5: GameEvent[] = [
  ev(
    'e001',
    1,
    5,
    '문밖의 발자국',
    '밖에 사람의 발자국이 남아 있다.',
    'danger',
    [
      roll('check', '확인한다', 70, [food(1)], '발자국을 따라가니 식량을 발견했다.', [status('injured', true)], '무언가에 걸려 넘어졌다. 부상을 입었다.'),
      c('ignore', '무시한다', [mental(2)], '신경 쓰지 않기로 했다. 마음이 조금 편해졌다.'),
      c('lock', '문을 잠근다', [shelter(5)], '문단속을 단단히 했다.'),
    ],
    { fixed: true },
  ),
  ev(
    'e002',
    1,
    ENDLESS_DAY_MAX,
    '새는 수도관',
    '벽에서 물이 새고 있다.',
    'resource',
    [
      c('catch', '받는다', [water(2), shelter(-5)], '그릇에 물을 받았다. 벽은 조금 상했다.'),
      c('fix', '수리한다', [shelter(5)], '수리했다.', { item: 'toolbox' }),
      c('leave', '무시한다', [shelter(-10)], '결국 내구도가 더 상했다.'),
    ],
    { repeatable: true, cooldownDays: 3 },
  ),
  ev(
    'e003',
    1,
    5,
    '약한 라디오',
    '잡음 사이로 사람 목소리가 들리는 것 같다.',
    'story',
    [
      c('listen', '주파수를 맞춰 본다', [info(10), counter('radioStory', 1)], '희미하지만 분명한 목소리였다. 정보를 얻었다.', { item: 'radio' }),
      c('noRadio', '라디오가 없다', [], '아무것도 확인하지 못했다.'),
    ],
    { fixed: true },
  ),
  ev(
    'e004',
    1,
    5,
    '통조림 하나',
    '구석에서 통조림을 발견했다.',
    'resource',
    [
      c('eat', '바로 먹는다', [hp(5)], '따뜻하진 않지만 배는 채웠다.'),
      c('store', '저장한다', [food(1)], '나중을 위해 아껴 두었다.'),
      c('drop', '버린다', [mental(2)], '괜히 홀가분했다.'),
    ],
  ),
  ev(
    'e005',
    1,
    5,
    '이상한 냄새',
    '대피소에서 타는 냄새가 은은하게 난다.',
    'danger',
    [
      c('inspect', '조사한다', [flag('electricChecked'), power(-2)], '낡은 배선 문제를 발견해 손을 봤다.'),
      c('vent', '환기한다', [mental(3)], '창을 열어 환기하니 한결 나았다.'),
      c('ignoreSmell', '무시한다', [flag('fireRisk')], '별일 아니겠거니 했다. 왠지 불안하다.'),
    ],
    { fixed: true },
  ),
  ev(
    'e006',
    1,
    5,
    '창밖의 불빛',
    '멀리서 손전등 같은 불빛이 움직인다.',
    'survival',
    [
      c('signal', '신호를 보낸다', [flag('signaledOutside')], '손전등을 두 번 깜빡였다. 저쪽에서도 반응이 있었다.'),
      c('ignoreLight', '무시한다', [], '아무 일도 일어나지 않았다.'),
      c('watch', '망원경으로 관찰한다', [info(5)], '누군가 이동하는 모습을 확인했다.', { item: 'binoculars' }),
    ],
  ),
  ev(
    'e007',
    1,
    5,
    '잠을 잘 수 없다',
    '밤새 이상한 소리가 들려 뒤척인다.',
    'survival',
    [
      c('watchNight', '경계한다', [mental(-2)], '뜬눈으로 밤을 지새웠다.'),
      roll('sleep', '그냥 잔다', 80, [hp(8)], '푹 잤다.', [hp(-10), shelter(-5)], '자는 사이 무언가 대피소를 건드렸다.'),
    ],
  ),
  ev(
    'e008',
    1,
    ENDLESS_DAY_MAX,
    '작은 상처',
    '탐색 중 손을 다쳤다.',
    'survival',
    [
      c('treatNow', '즉시 붕대를 감는다', [], '상처를 바로 처치했다.', { item: 'bandage' }),
      c('leaveIt', '그냥 둔다', [status('injured', true)], '일단 부상 상태가 되었다.'),
    ],
    { repeatable: true, cooldownDays: 3 },
  ),
  ev(
    'e009',
    1,
    5,
    '오래된 신문',
    '오래된 신문에서 재난 발생일에 대한 기사를 발견했다.',
    'story',
    [c('read', '읽어 본다', [info(5)], '재난 초기의 정황을 알게 되었다.')],
  ),
  ev(
    'e010',
    1,
    5,
    '비',
    '밖에 비가 내린다.',
    'resource',
    [
      c('filterRain', '정수해서 받는다', [water(3)], '깨끗한 물을 받았다.', { item: 'filter' }),
      c('rawRain', '그냥 받는다', [water(3), contamination(5)], '일단 받았지만 물이 조금 탁하다.'),
    ],
  ),
  ev(
    'e011',
    1,
    ENDLESS_DAY_MAX,
    '쥐',
    '대피소 안에 쥐가 나타났다.',
    'survival',
    [
      c('catchRat', '잡는다', [food(1)], '식량으로 삼았다.', { item: 'knife' }),
      c('shooRat', '쫓아낸다', [mental(1)], '내보냈다.'),
      c('leaveRat', '방치한다', [food(-1)], '식량을 축냈다.'),
    ],
    { repeatable: true, cooldownDays: 3 },
  ),
  ev(
    'e012',
    1,
    5,
    '이상한 소리',
    '벽 안쪽에서 두드리는 소리가 난다.',
    'rare',
    [
      c('breakWall', '벽을 뜯는다', [item('battery', 1), flag('wallOpened')], '숨겨진 배터리를 찾았다.', { item: 'toolbox' }),
      c('ignoreWall', '무시한다', [flag('wallNoise')], '신경 쓰지 않기로 했다.'),
    ],
  ),
  ev('e013', 1, 5, '낡은 배터리', '구석에서 배터리를 발견했다.', 'resource', [c('take013', '챙긴다', [item('battery', 2)], '배터리 2개를 얻었다.')]),
  ev(
    'e014',
    1,
    5,
    '식량 냄새',
    '어디선가 통조림 냄새가 난다.',
    'resource',
    [c('find014', '따라가 본다', [food(1)], '냄새를 따라가니 통조림이 있었다.')],
  ),
  ev(
    'e015',
    1,
    5,
    '첫 번째 악몽',
    '재난 직전의 기억을 꿈으로 꾸었다.',
    'story',
    [c('dream015', '식은땀을 닦는다', [mental(-5), info(3)], '흐릿했던 기억의 조각이 떠올랐다.')],
  ),
  ev(
    'e016',
    1,
    5,
    '정체불명의 노크',
    '문을 세 번 두드리는 소리가 났다.',
    'danger',
    [
      c('open016', '연다', [flag('visitorMet')], '문을 여니 아무도 없었다. 대신 발자국만 남아 있었다.'),
      c('answer016', '대답만 한다', [trust(2)], '대답하니 조용해졌다.'),
      c('ignore016', '무시한다', [mental(-3)], '끝내 대답하지 않았다. 마음이 무겁다.'),
    ],
    { fixed: true },
  ),
  ev(
    'e017',
    1,
    5,
    '깨진 창문',
    '창문이 깨졌다.',
    'danger',
    [
      c('fixWindow', '판자로 막는다', [shelter(5)], '판자로 막아 보강했다.', { item: 'toolbox' }),
      c('leaveWindow', '방치한다', [shelter(-10)], '찬 바람이 계속 들어온다.'),
    ],
  ),
  ev(
    'e018',
    1,
    5,
    '식수 확인',
    '보관 중인 물을 확인한다.',
    'resource',
    [
      c('cleanWater', '정화한다', [contamination(-10)], '정수 필터로 오염을 제거했다.', { item: 'filter' }),
      c('discardWater', '의심스러운 만큼 버린다', [water(-1)], '아까웠지만 버렸다.'),
    ],
  ),
  ev(
    'e019',
    1,
    5,
    '오래된 사진',
    '누군가의 가족사진을 발견했다.',
    'story',
    [c('keepPhoto', '챙긴다', [info(2), mental(3)], '낯선 가족의 웃는 얼굴이 위안이 됐다.')],
  ),
  ev(
    'e020',
    1,
    5,
    '비상식량',
    '숨겨진 식량 창고를 발견했다.',
    'rare',
    [c('stockpile', '전부 챙긴다', [food(3)], '뜻밖의 큰 수확이었다.')],
    { fixed: true },
  ),
]

// ============================== DAY 6~10 : 외부와의 접촉 ==============================
const DAY_6_10: GameEvent[] = [
  ev(
    'e021',
    6,
    10,
    '구조 요청',
    '무전기에서 구조 요청 신호가 잡힌다.',
    'story',
    [c('receive021', '수신한다', [info(10), counter('radioStory', 1)], '좌표 일부를 받아 적었다.', { item: 'walkie' })],
    { fixed: true, requires: (s) => (s.inventory.walkie ?? 0) > 0 },
  ),
  ev(
    'e022',
    6,
    10,
    '생존자',
    '문밖에서 여성이 도움을 요청한다.',
    'story',
    [
      c('welcome022', '들인다', [survivorJoin(), trust(10)], '떨고 있던 그녀를 안으로 들였다.'),
      c('refuse022', '거절한다', [mental(-5)], '문을 열지 않았다. 마음이 편치 않다.'),
      c('ask022', '질문한다', [info(5)], '문틈으로 몇 가지를 물었다.'),
    ],
    { fixed: true },
  ),
  ev(
    'e023',
    6,
    10,
    '아이의 목소리',
    '밖에서 아이 울음소리가 들린다.',
    'danger',
    [
      roll('goOut023', '나간다', 60, [survivorJoin('civilian')], '길 잃은 아이를 데려왔다.', [hp(-15), status('injured', true)], '함정이었다. 다쳤다.'),
      c('wait023', '기다린다', [flag('childWaiting')], '일단 기다려 보기로 했다.'),
      c('ignore023', '무시한다', [mental(-8)], '외면했다. 오래도록 마음에 남을 것 같다.'),
    ],
  ),
  ev(
    'e024',
    6,
    10,
    '편의점 발견',
    '가까운 편의점이 아직 무너지지 않았다.',
    'resource',
    [roll('explore024', '탐색한다', 75, [food(2), water(2)], '식량과 물을 챙겼다.', [status('injured', true)], '진열대가 무너지며 다쳤다.')],
  ),
  ev(
    'e025',
    6,
    10,
    '병원',
    '병원 건물이 보인다.',
    'resource',
    [roll('explore025', '탐색한다', 60, [item('medicine', 2), item('bandage', 2)], '의약품을 확보했다.', [status('injured', true)], '유리 파편에 다쳤다.')],
  ),
  ev(
    'e026',
    6,
    10,
    '이상한 감염',
    '생존자 한 명에게 열이 오른다.',
    'danger',
    [
      c('cure026', '치료한다', [survivorHp(20)], '의약품으로 열을 내렸다.', { item: 'medicine' }),
      c('noCure026', '지켜본다', [survivorHp(-20)], '상태가 나빠졌다.'),
    ],
    { requires: (s) => s.survivors.some((sv) => sv.alive) },
  ),
  ev(
    'e027',
    6,
    ENDLESS_DAY_MAX,
    '약탈자',
    '무기를 든 사람들이 밖에 나타났다.',
    'danger',
    [
      c('hide027', '숨는다', [mental(-5)], '숨죽인 채 지나가길 기다렸다.'),
      c('negotiate027', '협상한다', [food(-2)], '식량을 나눠 주고 돌려보냈다.'),
      roll('fight027', '맞선다', 55, [shelter(-5)], '몰아냈다. 대피소가 약간 상했다.', [hp(-20), shelter(-15)], '크게 다치고 대피소도 부서졌다.', { item: 'axe' }),
    ],
    { repeatable: true, cooldownDays: 3 },
  ),
  ev('e028', 6, 10, '발전기 소리', '밖에서 발전기 소리가 들린다.', 'story', [c('note028', '방향을 기록한다', [info(5)], '소리가 나는 방향을 지도에 표시했다.')]),
  ev(
    'e029',
    6,
    ENDLESS_DAY_MAX,
    '정전',
    '갑자기 전력이 나갔다.',
    'danger',
    [
      c('genFix029', '발전기로 버틴다', [power(5)], '발전기 덕에 큰 피해는 없었다.', { item: 'generator' }),
      c('darkNight029', '어둠 속에서 버틴다', [power(-10), mental(-3)], '불안한 밤을 보냈다.'),
    ],
    { repeatable: true, cooldownDays: 3 },
  ),
  ev(
    'e030',
    6,
    ENDLESS_DAY_MAX,
    '폭우',
    '밤새 비가 거세게 내린다.',
    'danger',
    [
      c('filterRain030', '정수 필터로 받는다', [water(3), shelter(-5)], '물은 확보했지만 지붕이 약간 상했다.', { item: 'filter' }),
      c('rawRain030', '그냥 버틴다', [shelter(-15)], '대피소 내구도가 크게 상했다.'),
    ],
    { repeatable: true, cooldownDays: 3 },
  ),
  ev(
    'e031',
    6,
    10,
    '라디오 방송',
    '"북쪽으로 이동하지 마십시오." 라디오에서 반복되는 경고가 흘러나온다.',
    'story',
    [c('heed031', '기록해 둔다', [info(10), counter('radioStory', 1)], '불길한 경고를 수첩에 옮겨 적었다.', { item: 'radio' })],
    { requires: (s) => (s.inventory.radio ?? 0) > 0 },
  ),
  ev(
    'e032',
    6,
    10,
    '거짓말',
    '생존자가 무언가를 숨기는 눈치다.',
    'story',
    [
      c('press032', '추궁한다', [trust(-10)], '분위기가 싸늘해졌다.'),
      c('watch032', '관찰만 한다', [info(5)], '단서를 조금 모았다.'),
      c('trustEvent032', '믿기로 한다', [trust(10)], '캐묻지 않기로 했다.'),
    ],
    { requires: (s) => s.survivors.some((sv) => sv.alive) },
  ),
  ev(
    'e033',
    6,
    10,
    '비밀 식량',
    '생존자가 식량을 몰래 숨겨 뒀던 걸 발견했다.',
    'story',
    [c('confront033', '알게 됐다', [food(2), trust(-15)], '식량은 되찾았지만 신뢰는 잃었다.')],
    { requires: (s) => s.survivors.some((sv) => sv.alive) },
  ),
  ev(
    'e034',
    6,
    10,
    '손전등 신호',
    '밖에서 불빛이 세 번 깜빡인다.',
    'story',
    [
      c('decode034', '암호를 확인한다', [info(5), flag('signalDecoded')], '규칙적인 패턴이었다. 신호처럼 보인다.', { item: 'binoculars' }),
      c('noBino034', '망원경이 없다', [], '너무 멀어 확인할 수 없었다.'),
    ],
  ),
  ev(
    'e035',
    6,
    10,
    '지도 발견',
    '지도에 표시되지 않은 장소가 있다.',
    'rare',
    [c('markMap035', '표시해 둔다', [flag('hiddenSpotKnown'), info(5)], '지도에 없는 장소를 알게 됐다.', { item: 'map' })],
    { requires: (s) => (s.inventory.map ?? 0) > 0 },
  ),
  ev(
    'e036',
    6,
    10,
    '환풍구',
    '환풍구를 통해 외부 공기가 들어온다.',
    'danger',
    [
      c('mask036', '마스크를 쓴다', [], '안전하게 확인했다.', { item: 'mask' }),
      roll('noMask036', '그냥 확인한다', 50, [], '별일 없었다.', [contamination(10)], '탁한 공기를 들이마셨다.'),
    ],
  ),
  ev(
    'e037',
    6,
    10,
    '라디오 잡음',
    '특정 주파수에서 이상한 숫자가 반복해서 들린다.',
    'story',
    [c('numbers037', '숫자를 받아 적는다', [info(10), counter('radioStory', 1)], '의미를 알 수 없는 숫자열을 기록했다.', { item: 'radio' })],
    { requires: (s) => (s.inventory.radio ?? 0) > 0 },
  ),
  ev(
    'e038',
    6,
    10,
    '낙서',
    '벽에 누군가 급하게 남긴 글씨가 있다. "문밖에서 부르는 소리가 들려도 열지 마."',
    'story',
    [c('read038', '읽는다', [flag('doorWarning'), mental(-3)], '누가 남겼을지 모를 경고가 마음에 박혔다.')],
    { fixed: true },
  ),
  ev(
    'e039',
    6,
    10,
    '실종',
    '생존자 한 명이 사라졌다.',
    'danger',
    [c('missing039', '흔적을 찾는다', [mental(-10), survivorLeave()], '끝내 찾지 못했다.')],
    { requires: (s) => s.survivors.some((sv) => sv.alive) },
  ),
  ev(
    'e040',
    6,
    10,
    '밤의 방문자',
    '문밖에 누군가 조용히 서 있다.',
    'danger',
    [
      c('openDoor040', '문을 연다', [hp(-10)], '경계할 새도 없이 밀쳐졌다.'),
      c('watch040', '망원경으로 관찰한다', [info(5)], '누구인지 확인했다.', { item: 'binoculars' }),
      c('ignore040', '무시한다', [], '기척이 사라졌다.'),
    ],
  ),
]

// ============================== DAY 11~15 : 위기 ==============================
const DAY_11_15: GameEvent[] = [
  ev(
    'e041',
    11,
    ENDLESS_DAY_MAX,
    '물 부족',
    '비축된 물이 눈에 띄게 줄었다.',
    'resource',
    [c('note041', '아껴 쓰기로 한다', [water(-1)], '오늘은 평소보다 아껴 마셨다.')],
    { repeatable: true, cooldownDays: 3 },
  ),
  ev(
    'e042',
    11,
    ENDLESS_DAY_MAX,
    '식량 배급',
    '식량이 부족해 나눠야 할 상황이다.',
    'resource',
    [
      c('share042', '나눠 먹는다', [food(-2), mental(5, )], '다 함께 나눠 먹었다. 분위기가 한결 나아졌다.'),
      c('keep042', '혼자 먹는다', [trust(-10)], '눈치가 보였다.'),
    ],
    { requires: (s) => s.survivors.some((sv) => sv.alive), repeatable: true, cooldownDays: 3 },
  ),
  ev(
    'e043',
    11,
    ENDLESS_DAY_MAX,
    '부상 악화',
    '치료하지 않은 상처가 욱신거린다.',
    'danger',
    [c('worse043', '버틴다', [hp(-10)], '상처가 덧났다.')],
    { requires: (s) => s.statusEffects.injured, repeatable: true, cooldownDays: 3 },
  ),
  ev(
    'e044',
    11,
    ENDLESS_DAY_MAX,
    '대피소 균열',
    '벽에 큰 균열이 생겼다.',
    'danger',
    [
      c('fix044', '공구상자로 보강한다', [shelter(-10)], '피해를 최소화했다.', { item: 'toolbox' }),
      c('nofix044', '어쩔 도리가 없다', [shelter(-20)], '균열이 더 커졌다.'),
    ],
    { repeatable: true, cooldownDays: 3 },
  ),
  ev(
    'e045',
    11,
    ENDLESS_DAY_MAX,
    '화재',
    '한쪽 구석에서 불씨가 일었다.',
    'danger',
    [
      c('extinguish045', '소화한다', [shelter(-5)], '빠르게 진화했다.', { item: 'matches' }),
      roll('escape045', '탈출한다', 60, [], '무사히 피했다.', [survivorLeave()], '혼란 속에 한 명을 놓쳤다.', { survivor: true }),
      c('leaveFire045', '방치한다', [shelter(-30)], '피해가 크게 번졌다.'),
    ],
    { repeatable: true, cooldownDays: 3 },
  ),
  ev(
    'e046',
    11,
    15,
    '병원 약품',
    '병원을 다시 찾아가 본다.',
    'resource',
    [roll('reexplore046', '탐색한다', 55, [item('medicine', 3)], '의약품을 넉넉히 확보했다.', [status('injured', true)], '무너진 잔해에 다쳤다.')],
  ),
  ev(
    'e047',
    11,
    15,
    '이상한 환자',
    '병원에서 홀로 남은 환자를 발견했다.',
    'rare',
    [
      c('bring047', '데려온다', [survivorJoin('doctor')], '알고 보니 이 병원의 의사였다.'),
      c('leave047', '두고 온다', [mental(-3)], '혼자 남겨 두고 왔다.'),
    ],
  ),
  ev(
    'e048',
    11,
    15,
    '군용 차량',
    '길가에 버려진 군용 차량이 있다.',
    'story',
    [roll('search048', '수색한다', 55, [item('battery', 1), info(5)], '배터리와 기록 일부를 확보했다.', [status('injured', true)], '날카로운 파편에 다쳤다.')],
    { fixed: true },
  ),
  ev(
    'e049',
    11,
    15,
    '군용 기록',
    '차량 안에서 기록물을 발견했다.',
    'story',
    [c('readRecord049', '읽는다', [info(15), flag('militaryRecord')], '재난 초기 군의 대응 기록이었다.')],
    { requires: (s) => s.firedEventIds.includes('e048'), fixed: true },
  ),
  ev(
    'e050',
    11,
    ENDLESS_DAY_MAX,
    '검은 비',
    '검은빛을 띠는 비가 내린다.',
    'danger',
    [
      c('protect050', '마스크와 필터로 대비한다', [contamination(5)], '피해를 줄였다.', { item: 'mask' }),
      c('exposed050', '그대로 맞는다', [contamination(20)], '오염 수치가 크게 올랐다.'),
    ],
    { repeatable: true, cooldownDays: 3 },
  ),
  ev(
    'e051',
    11,
    15,
    '오염',
    '몸 상태가 이상하다.',
    'danger',
    [c('checkContam051', '상태를 확인한다', [], '오염 수치에 따라 몸이 반응하고 있다.')],
    { requires: (s) => s.stats.contamination >= 50 },
  ),
  ev(
    'e052',
    11,
    15,
    "생존자의 고백",
    '생존자가 재난에 대해 알고 있는 것이 있다고 털어놓는다.',
    'story',
    [c('confess052', '듣는다', [info(15), trust(10)], '전에 어디선가 일하고 있었다는 이야기를 들었다.')],
    { requires: (s) => s.survivors.some((sv) => sv.alive), fixed: true },
  ),
  ev(
    'e053',
    11,
    15,
    '거짓 구조대',
    '구조대를 자처하는 이들이 방송을 보낸다.',
    'story',
    [
      c('seeThrough053', '거짓임을 알아챈다', [info(5)], '앞뒤가 맞지 않는 부분을 짚어냈다.', { infoMin: 40 }),
      c('believe053', '믿어 본다', [mental(-5)], '기대했지만 아무도 오지 않았다.'),
    ],
  ),
  ev(
    'e054',
    11,
    15,
    '식량 도둑',
    '보관해 둔 식량이 사라졌다.',
    'danger',
    [c('investigate054', '조사한다', [food(-2), trust(-5)], '범인은 끝내 밝히지 못했다.')],
  ),
  ev(
    'e055',
    11,
    15,
    '비밀 통로',
    '대피소 벽 뒤에서 좁은 통로를 발견했다.',
    'rare',
    [c('open055', '통로를 연다', [flag('secretPassage'), info(5)], '어디로 이어지는지 모를 통로였다.')],
  ),
  ev(
    'e056',
    11,
    15,
    '오래된 기록',
    '재난 이전의 연구 기록을 발견했다.',
    'story',
    [c('read056', '읽는다', [info(15)], '재난 발생 이전의 이상한 연구 기록이었다.')],
  ),
  ev(
    'e057',
    11,
    15,
    '이상한 전파',
    '라디오에서 사람 목소리가 아닌 소리가 흘러나온다.',
    'danger',
    [c('listen057', '끝까지 듣는다', [mental(-10)], '설명할 수 없는 불쾌한 소리였다.', { item: 'radio' })],
    { requires: (s) => (s.inventory.radio ?? 0) > 0 },
  ),
  ev(
    'e058',
    11,
    15,
    '구조 헬기',
    '하늘에서 헬기 소리가 들린다.',
    'danger',
    [
      c('signal058', '신호를 보낸다', [flag('helicopterSignaled')], '있는 힘껏 신호를 보냈지만 헬기는 그대로 지나갔다.'),
      c('hide058', '숨는다', [], '안전하게 지나가길 기다렸다.'),
    ],
  ),
  ev(
    'e059',
    11,
    15,
    '식수 정화',
    '오염된 물을 정화할 수 있다.',
    'resource',
    [c('purify059', '정수한다', [contamination(-20), water(1)], '깨끗한 물을 조금 더 확보했다.', { item: 'filter' })],
    { requires: (s) => (s.inventory.filter ?? 0) > 0 },
  ),
  ev(
    'e060',
    15,
    15,
    '15일째',
    '"15일째. 절반을 버텼다." 라디오에서 낮은 목소리가 흘러나온다. "구조는 오지 않는다."',
    'story',
    [c('accept060', '받아들인다', [info(20), mental(-5)], '무거운 확신이 마음에 내려앉았다.')],
    { fixed: true },
  ),
]

// ============================== DAY 16~20 : 진실에 접근 ==============================
const DAY_16_20: GameEvent[] = [
  ev(
    'e061',
    16,
    20,
    '북쪽 신호',
    '북쪽에서 구조 신호가 잡힌다.',
    'story',
    [c('north061', '방향을 기록한다', [routeEff('north'), info(5)], '북쪽 루트가 지도에 표시됐다.')],
  ),
  ev(
    'e062',
    16,
    20,
    '남쪽 신호',
    '남쪽에서 식량 관련 신호가 잡힌다.',
    'story',
    [c('south062', '방향을 기록한다', [routeEff('south'), info(5)], '남쪽 루트가 지도에 표시됐다.')],
  ),
  ev(
    'e063',
    16,
    20,
    '두 신호',
    '북쪽과 남쪽, 두 신호가 동시에 들어온다. 하나를 선택해야 한다.',
    'story',
    [
      c('chooseNorth063', '북쪽을 택한다', [routeEff('north'), flag('routeChosen')], '북쪽 공동체 쪽으로 방향을 정했다.'),
      c('chooseSouth063', '남쪽을 택한다', [routeEff('south'), flag('routeChosen')], '남쪽 군사 시설 쪽으로 방향을 정했다.'),
    ],
  ),
  ev(
    'e064',
    16,
    20,
    '북쪽 공동체',
    '북쪽 루트를 따라가니 생존자 집단이 있었다는 흔적이 있다.',
    'story',
    [c('found064', '흔적을 조사한다', [info(10), trust(5)], '사람이 살았던 흔적이 또렷했다.')],
    { requires: (s) => s.route === 'north' },
  ),
  ev(
    'e065',
    16,
    20,
    '남쪽 기지',
    '남쪽 루트를 따라가니 군사 시설 흔적이 있다.',
    'story',
    [c('found065', '흔적을 조사한다', [info(10), flag('militaryRecord')], '버려진 군사 시설이었다.')],
    { requires: (s) => s.route === 'south' },
  ),
  ev(
    'e066',
    16,
    20,
    '배신',
    '신뢰가 낮았던 생존자가 자원을 훔쳐 사라졌다.',
    'danger',
    [c('betrayed066', '피해를 확인한다', [food(-3), water(-3), survivorLeave()], '가장 믿지 못했던 사람이었다.')],
    { requires: (s) => s.survivors.some((sv) => sv.alive && sv.trust < 40) },
  ),
  ev(
    'e067',
    16,
    20,
    '협력',
    '신뢰가 높은 생존자가 자신의 비상식량을 나눠 준다.',
    'story',
    [c('helped067', '고맙게 받는다', [food(2), mental(5)], '뜻밖의 온기였다.')],
    { requires: (s) => s.survivors.some((sv) => sv.alive && sv.trust >= 60) },
  ),
  ev(
    'e068',
    16,
    20,
    'CCTV',
    '발전기로 전력을 넣으니 오래된 CCTV 저장 장치가 켜진다.',
    'story',
    [c('watchCctv068', '영상을 확인한다', [info(20), power(-5)], '재난 당일의 장면이 담겨 있었다.', { item: 'generator' })],
    { fixed: true, requires: (s) => (s.inventory.generator ?? 0) > 0 },
  ),
  ev(
    'e069',
    16,
    20,
    '연구원 기록',
    '지하 연구시설에 관한 기록을 발견했다.',
    'story',
    [c('read069', '읽는다', [info(10), flag('researchRecord')], '시설의 존재를 확신하게 됐다.')],
  ),
  ev(
    'e070',
    16,
    20,
    '이름',
    '기록에 등장하는 연구원의 이름이, 예전에 만났던 생존자의 이름과 같다.',
    'story',
    [c('realize070', '기록을 다시 확인한다', [info(10)], '우연이라기엔 너무 정확히 일치했다.')],
    { requires: (s) => s.flags.researchRecord === true },
  ),
  ev(
    'e071',
    16,
    20,
    '실험실',
    '지도에 없던 지하 연구시설 입구를 찾았다.',
    'danger',
    [
      roll(
        'exploreLab071',
        '진입한다',
        25,
        [flag('labExplored'), info(15)],
        '깊숙한 곳까지 들어가 무언가를 확인했다.',
        [hp(-20), status('injured', true)],
        '무너진 통로에 크게 다쳤다.',
      ),
    ],
  ),
  ev(
    'e072',
    16,
    20,
    '이상한 약',
    '연구실에서 정체 모를 약을 발견했다.',
    'rare',
    [roll('takeDrug072', '복용한다', 80, [hp(30)], '몸 상태가 눈에 띄게 좋아졌다.', [mental(-20)], '알 수 없는 부작용에 시달렸다.')],
    { requires: (s) => s.flags.labExplored === true },
  ),
  ev(
    'e073',
    16,
    20,
    '냉동실',
    '연구시설 안쪽, 냉동 보관된 무언가를 발견했다.',
    'story',
    [c('findFreezer073', '확인한다', [flag('freezerSeen'), mental(-10)], '무엇인지는 알 수 없지만, 보지 말았어야 했다는 생각이 들었다.')],
    { requires: (s) => s.flags.labExplored === true, fixed: true },
  ),
  ev(
    'e074',
    16,
    20,
    '검은 상자',
    '군용 블랙박스를 발견했다.',
    'story',
    [c('openBox074', '연다', [info(20), flag('blackBox')], '재난 직전의 영상 기록이 담겨 있었다.')],
    { requires: (s) => s.flags.militaryRecord === true, fixed: true },
  ),
  ev(
    'e075',
    16,
    20,
    '마지막 명령',
    '블랙박스 속 마지막 명령이 재생된다. "모든 대피소를 폐쇄하라."',
    'story',
    [c('hearOrder075', '끝까지 듣는다', [info(15), mental(-5)], '누구의 명령이었는지는 나오지 않았다.')],
    { requires: (s) => s.flags.blackBox === true },
  ),
  ev(
    'e076',
    16,
    20,
    '탈출 차량',
    '연료가 조금 남은 차량을 발견했다.',
    'story',
    [c('readyVehicle076', '정비해 둔다', [flag('escapeVehicleReady')], '언제든 떠날 수 있게 준비해 두었다.', { item: 'generator' })],
    { requires: (s) => (s.inventory.generator ?? 0) > 0 },
  ),
  ev(
    'e077',
    16,
    20,
    '동료의 결정',
    '생존자 한 명이 대피소를 떠나겠다고 말한다.',
    'story',
    [
      c('letGo077', '보내준다', [survivorLeave(), trust(5)], '뜻을 존중하기로 했다.'),
      c('keep077', '붙잡는다', [survivorTrust(10)], '설득 끝에 남기로 했다.'),
    ],
    { requires: (s) => s.survivors.some((sv) => sv.alive) },
  ),
  ev(
    'e078',
    16,
    ENDLESS_DAY_MAX,
    '밤의 습격',
    '약탈자들이 대피소를 습격한다.',
    'danger',
    [
      c('guardedFight078', '맞서 싸운다', [shelter(-10)], '경계 태세 덕에 피해를 줄였다.', { item: 'axe' }),
      roll('fight078', '맞서 싸운다', 50, [shelter(-15)], '겨우 몰아냈다.', [hp(-20), shelter(-30)], '큰 피해를 입었다.'),
    ],
    { repeatable: true, cooldownDays: 3 },
  ),
  ev(
    'e079',
    16,
    20,
    '무전기의 좌표',
    '무전기에서 알 수 없는 좌표가 반복해서 들려온다.',
    'story',
    [c('recordCoord079', '좌표를 기록한다', [flag('finalCoordKnown'), info(10)], '최종 목적지로 보이는 좌표를 얻었다.', { item: 'walkie' })],
    { fixed: true, requires: (s) => (s.inventory.walkie ?? 0) > 0 },
  ),
  ev(
    'e080',
    20,
    20,
    '20일째',
    '"20일째." 정보가 충분하다면 다음 문장이 이어진다 — "재난은 아직 끝나지 않았다."',
    'story',
    [c('milestone080', '되새긴다', [mental(-3)], '남은 열흘이 유독 길게 느껴졌다.')],
    { fixed: true },
  ),
]

// ============================== DAY 21~25 : 최종장 ==============================
const DAY_21_25: GameEvent[] = [
  ev(
    'e081',
    21,
    ENDLESS_DAY_MAX,
    '대규모 폭풍',
    '역대급 폭풍이 대피소를 덮친다.',
    'danger',
    [c('storm081', '버틴다', [shelter(-20, )], '지붕 일부가 뜯겨 나갔다.')],
    { repeatable: true, cooldownDays: 3 },
  ),
  ev(
    'e082',
    21,
    25,
    '물 오염',
    '보관해 둔 물의 절반가량이 오염됐다.',
    'danger',
    [
      c('filterSafe082', '필터로 막아 냈다', [], '정수 필터 덕분에 무사했다.', { item: 'filter' }),
      c('loseWater082', '피해를 본다', [water(-2), contamination(10)], '아까운 물을 버려야 했다.'),
    ],
  ),
  ev(
    'e083',
    21,
    25,
    '생존자 감염',
    '생존자 한 명이 감염 증세를 보인다.',
    'danger',
    [
      c('cure083', '의약품으로 치료한다', [status('infected', false)], '고비를 넘겼다.', { item: 'medicine' }),
      c('noMed083', '지켜볼 수밖에 없다', [survivorHp(-20), status('infected', true)], '상태가 급격히 나빠졌다.'),
    ],
    { requires: (s) => s.survivors.some((sv) => sv.alive) },
  ),
  ev(
    'e084',
    21,
    ENDLESS_DAY_MAX,
    '대피소 습격',
    '이제까지와는 다른, 조직적인 습격이다.',
    'danger',
    [
      c('weaponFight084', '무장하고 맞선다', [hp(-10), shelter(-15)], '무기 덕에 피해를 줄였다.', { item: 'axe' }),
      roll('bareFight084', '맨몸으로 맞선다', 40, [shelter(-20)], '가까스로 버텼다.', [hp(-30), shelter(-30)], '심각한 피해를 입었다.'),
    ],
    { repeatable: true, cooldownDays: 3 },
  ),
  ev('e085', 21, 25, '식량 창고', '대량의 식량이 남아 있는 창고를 발견했다.', 'resource', [roll('bigFood085', '탐색한다', 55, [food(5)], '많은 식량을 확보했다.', [status('injured', true)], '무너진 선반에 다쳤다.')]),
  ev(
    'e086',
    21,
    25,
    '마지막 구조 신호',
    '구조 신호가 마지막으로 잡힌다.',
    'story',
    [c('finalSignal086', '위치를 확인한다', [flag('finalLocationKnown'), info(10)], '최종 지역의 위치가 드러났다.')],
    { fixed: true },
  ),
  ev(
    'e087',
    21,
    25,
    '탈출 준비',
    '탈출에 필요한 조건을 점검한다.',
    'story',
    [c('checkPrep087', '점검한다', [], '지금까지 모은 것들을 다시 확인했다.')],
  ),
  ev(
    'e088',
    21,
    25,
    '동료의 희생',
    '동료 한 명이 플레이어를 위해 이곳에 남겠다고 한다.',
    'story',
    [
      c('acceptSacrifice088', '뜻을 받아들인다', [survivorLeave(), flag('survivorSacrificed'), mental(-10)], '끝내 말리지 못했다.'),
      c('refuseSacrifice088', '함께 가자고 붙잡는다', [survivorTrust(15), mental(5)], '함께 가기로 했다.'),
    ],
    { requires: (s) => s.survivors.some((sv) => sv.alive) },
  ),
  ev(
    'e089',
    21,
    25,
    '진실의 문',
    '지금까지 모은 정보가 하나로 이어지기 시작한다.',
    'story',
    [c('openTruth089', '끝까지 파고든다', [flag('truthDoor'), info(5)], '재난의 전모에 조금 더 가까워졌다.')],
    { requires: (s) => s.stats.info >= 70, fixed: true },
  ),
  ev(
    'e090',
    25,
    25,
    '25일째',
    '"5일 남았다." 이 순간부터 모든 위험이 조금 더 날카로워진다.',
    'story',
    [c('milestone090', '각오를 다진다', [mental(-3)], '마지막 구간이 시작됐다.')],
    { fixed: true },
  ),
]

// ============================== DAY 26~29 : 최후 ==============================
const DAY_26_29: GameEvent[] = [
  ev(
    'e091',
    26,
    29,
    '마지막 식량',
    '식량이 거의 바닥났다. 누구에게 먼저 먹일지 정해야 한다.',
    'danger',
    [
      c('feedSelf091', '자신이 먹는다', [hp(5)], '스스로를 먼저 챙겼다.'),
      c('feedOthers091', '동료에게 먼저 먹인다', [survivorTrust(10), hp(-5)], '자신의 몫을 나눠 주었다.', { survivor: true }),
    ],
  ),
  ev(
    'e092',
    26,
    29,
    '마지막 물',
    '물이 거의 바닥났다.',
    'danger',
    [
      c('drinkSelf092', '본인이 마신다', [hp(5)], '갈증을 먼저 해결했다.'),
      c('saveWater092', '저장해 둔다', [water(1)], '아껴서 나눠 쓰기로 했다.'),
    ],
  ),
  ev(
    'e093',
    26,
    ENDLESS_DAY_MAX,
    '최후의 습격',
    '지금까지 중 가장 큰 규모의 습격이다.',
    'danger',
    [c('lastRaid093', '전력으로 방어한다', [shelter(-40)], '가까스로 버텼지만 대피소가 크게 상했다.')],
    { repeatable: true, cooldownDays: 3 },
  ),
  ev(
    'e094',
    26,
    29,
    '마지막 탐색',
    '이 근방에서의 마지막 탐색 기회다.',
    'rare',
    [roll('finalExplore094', '나선다', 50, [item('medicine', 1), info(10)], '중요한 물건을 손에 넣었다.', [status('injured', true)], '무리한 탐색에 다쳤다.')],
  ),
  ev(
    'e095',
    26,
    29,
    '탈출 경로',
    '지도와 정황을 종합하니 탈출 경로가 보인다.',
    'story',
    [c('routeReady095', '경로를 확정한다', [flag('escapeRouteReady')], '지도 위에 경로를 그렸다.')],
    { requires: (s) => (s.inventory.map ?? 0) > 0 && s.flags.finalLocationKnown === true },
  ),
  ev(
    'e096',
    29,
    29,
    '문득 스치는 밤',
    '아무 일도 일어나지 않는다. 대신 지금까지의 선택들이 머릿속을 스친다. "여기까지 버텼다."',
    'story',
    [c('reflect096', '지난 시간을 돌아본다', [mental(5)], '여기까지 왔다는 사실이 새삼스럽다.')],
    { fixed: true },
  ),
  ev(
    'e097',
    26,
    29,
    '이상한 방송',
    '라디오에서 낯선 목소리가 흘러나온다. 자신의 이름을 부르는 것 같다.',
    'story',
    [c('hearName097', '귀를 기울인다', [flag('finalBroadcast'), mental(-5)], '분명히 이름을 부르고 있었다.', { item: 'radio' })],
    { fixed: true, requires: (s) => (s.inventory.radio ?? 0) > 0 },
  ),
  ev(
    'e098',
    28,
    29,
    '문밖의 사람',
    '누군가 문밖에서 조용히 말한다. "이제 끝났습니다."',
    'danger',
    [
      c('open098', '문을 연다', [flag('doorOpenedEarly'), hp(-15)], '문을 여는 순간 무언가 잘못됐다는 걸 깨달았다.'),
      c('notOpen098', '문을 열지 않는다', [flag('doorHeld'), mental(-3)], '낙서의 경고를 떠올리며 버텼다.'),
    ],
    { fixed: true },
  ),
  ev(
    'e099',
    26,
    29,
    '마지막 기억',
    '모아 온 정보와 기록들이 하나의 장면으로 이어진다.',
    'story',
    [c('remember099', '기억을 마주한다', [flag('finalMemory'), info(5)], '재난 발생 직전, 스스로도 잊고 있던 순간이 떠올랐다.')],
    { requires: (s) => s.flags.truthDoor === true || s.flags.blackBox === true, fixed: true },
  ),
]

// ============================== 추가분 1 : 생존(survival) 카테고리 보강 ==============================
// 목마름/배고픔/부상/피로 같은 일상적인 생존 소모를 다루는 이벤트. 대부분 16일 이후,
// 특히 21일 이후에도 계속 반복돼서 엔드리스 구간의 밀도를 채운다.
const SURVIVAL_EXTRA: GameEvent[] = [
  ev(
    'e100',
    21,
    ENDLESS_DAY_MAX,
    '탈진 직전',
    '며칠째 제대로 쉬지 못했다. 몸이 자꾸 휘청인다.',
    'survival',
    [
      c('forceRest100', '무리해서라도 쉰다', [hp(5), mental(3)], '억지로라도 몸을 뉘였다. 조금은 나아졌다.'),
      c('pushOn100', '그래도 움직인다', [hp(-10), mental(-3)], '쉴 틈 없이 몸을 굴렸다. 몸이 더 상했다.'),
    ],
    { repeatable: true, cooldownDays: 3 },
  ),
  ev(
    'e101',
    16,
    ENDLESS_DAY_MAX,
    '손 떨림',
    '허기 탓인지 손이 자꾸 떨린다.',
    'survival',
    [
      c('eatSome101', '식량을 꺼내 먹는다', [item('can', -1), hunger(15)], '허겁지겁 먹고 나니 좀 진정됐다.', { item: 'can' }),
      c('endureHunger101', '참는다', [mental(-3)], '이를 악물고 버텼다.'),
    ],
    { repeatable: true, cooldownDays: 3, requires: (s) => s.stats.hunger < 40 },
  ),
  ev(
    'e102',
    16,
    ENDLESS_DAY_MAX,
    '갈라진 입술',
    '입술이 갈라질 만큼 목이 말랐다.',
    'survival',
    [
      c('drinkSome102', '물을 마신다', [item('water', -1), thirst(15)], '조금 마시니 갈증이 가셨다.', { item: 'water' }),
      c('endureThirst102', '참는다', [mental(-3)], '입술을 깨물며 버텼다.'),
    ],
    { repeatable: true, cooldownDays: 3, requires: (s) => s.stats.thirst < 40 },
  ),
  ev(
    'e103',
    21,
    ENDLESS_DAY_MAX,
    '쑤시는 관절',
    '오래 웅크려 지낸 탓에 삭신이 쑤신다.',
    'survival',
    [
      c('stretch103', '몸을 풀어 준다', [mental(3)], '스트레칭을 하니 한결 가뿐하다.'),
      c('ignoreAche103', '참고 넘긴다', [hp(-5)], '쑤시는 몸을 무시하고 넘겼다.'),
    ],
    { repeatable: true, cooldownDays: 4 },
  ),
  ev(
    'e104',
    16,
    ENDLESS_DAY_MAX,
    '곰팡이 냄새',
    '구석에서 곰팡이 냄새가 올라온다.',
    'survival',
    [
      c('clean104', '청소한다', [shelter(5)], '깨끗이 치우니 공기가 나아졌다.'),
      c('ignoreMold104', '무시한다', [contamination(5)], '그냥 넘겼다. 공기가 계속 텁텁하다.'),
    ],
    { repeatable: true, cooldownDays: 4 },
  ),
  ev(
    'e105',
    21,
    ENDLESS_DAY_MAX,
    '불면의 밤',
    '잠이 오지 않는 밤이 이어진다.',
    'survival',
    [
      roll('tryRest105', '억지로라도 눈을 붙인다', 60, [hp(5)], '그럭저럭 눈을 붙였다.', [mental(-5)], '뒤척이다 날이 밝았다.'),
      c('stayUp105', '그냥 깨어 있는다', [mental(-3)], '뜬눈으로 밤을 새웠다.'),
    ],
    { repeatable: true, cooldownDays: 3 },
  ),
  ev(
    'e106',
    21,
    ENDLESS_DAY_MAX,
    '체온 저하',
    '밤사이 기온이 뚝 떨어졌다.',
    'survival',
    [
      c('useBlanket106', '담요를 덮는다', [hp(5)], '담요 덕분에 몸을 녹였다.', { item: 'blanket' }),
      c('shiver106', '그냥 견딘다', [hp(-10)], '추위에 떨며 밤을 보냈다.'),
    ],
    { repeatable: true, cooldownDays: 4 },
  ),
  ev(
    'e107',
    26,
    ENDLESS_DAY_MAX,
    '굳은살',
    '손발에 굳은살이 박였다. 이제 이 생활에 익숙해진 걸까.',
    'survival',
    [
      c('acceptCallus107', '받아들인다', [mental(3)], '익숙해진 스스로를 발견했다.'),
      c('resistCallus107', '낯설어한다', [mental(-3)], '여전히 이 생활이 낯설다.'),
    ],
    { repeatable: true, cooldownDays: 3 },
  ),
  ev(
    'e108',
    21,
    25,
    '거울 속의 나',
    '우연히 거울에 비친 자신의 모습을 본다. 낯선 얼굴이다.',
    'survival',
    [
      c('accept108', '그런 자신을 받아들인다', [mental(5)], '변한 스스로를 인정하기로 했다.'),
      c('avert108', '눈을 돌린다', [mental(-5)], '차마 오래 보지 못하고 눈을 돌렸다.'),
    ],
    { fixed: true },
  ),
  ev(
    'e109',
    21,
    ENDLESS_DAY_MAX,
    '허기진 새벽',
    '허기가 심해져 정신이 아득해진다.',
    'survival',
    [
      c('emergencyEat109', '비상식량을 꺼낸다', [item('can', -1), hunger(20)], '급한 대로 배를 채웠다.', { item: 'can' }),
      c('collapse109', '그대로 버틴다', [hp(-10), mental(-5)], '헛구역질을 하며 버텼다.'),
    ],
    { repeatable: true, cooldownDays: 3, requires: (s) => s.stats.hunger < 25 },
  ),
  ev(
    'e110',
    16,
    ENDLESS_DAY_MAX,
    '얕은 잠',
    '선잠이 든 사이 이상한 꿈을 꿨다.',
    'survival',
    [
      c('shakeOff110', '털어 낸다', [mental(3)], '꿈일 뿐이라 여기고 털어냈다.'),
      c('dwell110', '계속 떠올린다', [mental(-3)], '꿈의 잔상이 하루 종일 남았다.'),
    ],
    { repeatable: true, cooldownDays: 3 },
  ),
  ev(
    'e111',
    21,
    ENDLESS_DAY_MAX,
    '말라붙은 목',
    '목이 바짝 말라 침을 삼키기도 힘들다.',
    'survival',
    [
      c('emergencyDrink111', '비상용 물을 마신다', [item('water', -1), thirst(20)], '급한 대로 갈증을 달랬다.', { item: 'water' }),
      c('endure111', '참고 버틴다', [hp(-10), mental(-5)], '현기증을 느끼며 버텼다.'),
    ],
    { repeatable: true, cooldownDays: 3, requires: (s) => s.stats.thirst < 25 },
  ),
  ev(
    'e112',
    21,
    ENDLESS_DAY_MAX,
    '손끝의 감각',
    '손끝 감각이 둔해졌다. 오래 씻지 못한 탓일까.',
    'survival',
    [
      c('washUp112', '물을 아껴 씻는다', [item('water', -1), mental(5)], '개운해졌다.', { item: 'water' }),
      c('stayDirty112', '그냥 넘긴다', [mental(-3)], '찝찝함을 참고 넘겼다.'),
    ],
    { repeatable: true, cooldownDays: 4 },
  ),
  ev(
    'e113',
    26,
    ENDLESS_DAY_MAX,
    '긴 하루의 끝',
    '또 하루가 저물었다. 며칠째인지 세는 것도 잊었다.',
    'survival',
    [
      roll('lookBack113', '지나온 날들을 헤아려 본다', 70, [mental(5)], '버텨온 날들이 헛되지 않았다고 느꼈다.', [mental(-5)], '막막함이 밀려왔다.'),
      c('justSleep113', '아무 생각 없이 잔다', [hp(5)], '생각을 비우고 그대로 잠들었다.'),
    ],
    { repeatable: true, cooldownDays: 3 },
  ),
]

// ============================== 추가분 2 : 동료 관계 이벤트 ==============================
// 살아 있는 동료가 있을 때만 뜨는, 신뢰도와 관계를 다루는 이벤트.
const COMPANION_EXTRA: GameEvent[] = [
  ev(
    'e114',
    11,
    20,
    '동료의 잠꼬대',
    '동료가 잠결에 누군가의 이름을 부른다.',
    'story',
    [
      c('listenQuiet114', '조용히 들어 준다', [survivorTrust(10)], '다음 날, 동료가 고맙다는 눈빛을 보냈다.'),
      c('wakeUp114', '깨운다', [survivorTrust(-5)], '놀라 깬 동료가 어색하게 사과했다.'),
    ],
    { requires: (s) => s.survivors.some((sv) => sv.alive) },
  ),
  ev(
    'e115',
    16,
    29,
    '말다툼',
    '사소한 일로 동료들 사이에 말다툼이 벌어졌다.',
    'story',
    [
      c('mediate115', '중재한다', [survivorTrust(10, 'all'), mental(-3)], '가까스로 갈등을 가라앉혔다.'),
      c('stayOut115', '끼어들지 않는다', [survivorTrust(-10, 'all')], '분위기가 한동안 냉랭했다.'),
    ],
    { requires: (s) => s.survivors.filter((sv) => sv.alive).length >= 2 },
  ),
  ev(
    'e116',
    11,
    25,
    '동료의 향수병',
    '동료가 말없이 어딘가를 바라보고 있다. 떠나온 곳이 그리운 모양이다.',
    'story',
    [
      c('talk116', '말을 걸어 본다', [survivorTrust(10), mental(3)], '속마음을 조금 나눴다.'),
      c('leaveAlone116', '혼자 두다', [], '그저 지켜보기만 했다.'),
    ],
    { requires: (s) => s.survivors.some((sv) => sv.alive) },
  ),
  ev(
    'e117',
    16,
    ENDLESS_DAY_MAX,
    '몫을 나누다',
    '동료가 자기 몫의 식량을 슬쩍 나눠 준다.',
    'survival',
    [
      c('acceptShare117', '받는다', [food(1), survivorTrust(5)], '고맙게 받았다.'),
      c('refuseShare117', '거절한다', [survivorTrust(10)], '괜찮다며 돌려주자 동료가 오히려 더 마음을 열었다.'),
    ],
    { repeatable: true, cooldownDays: 4, requires: (s) => s.survivors.some((sv) => sv.alive) },
  ),
  ev(
    'e118',
    16,
    ENDLESS_DAY_MAX,
    '동료가 아파 보인다',
    '동료 한 명이 안색이 좋지 않다.',
    'danger',
    [
      c('treat118', '약을 챙겨 준다', [survivorHp(10), survivorTrust(10)], '약을 먹고 한결 나아졌다.', { item: 'medicine' }),
      c('rest118', '일단 쉬게 한다', [survivorHp(5)], '무리하지 않게 쉬도록 했다.'),
    ],
    { repeatable: true, cooldownDays: 4, requires: (s) => s.survivors.some((sv) => sv.alive) },
  ),
  ev(
    'e119',
    16,
    29,
    '밤을 지키는 동료',
    '동료가 먼저 나서서 오늘 밤 경계를 서겠다고 한다.',
    'story',
    [
      c('letThem119', '맡긴다', [mental(5), survivorTrust(5)], '덕분에 오랜만에 푹 쉬었다.'),
      c('insistSelf119', '자신이 서겠다고 한다', [survivorTrust(10), mental(-3)], '대신 자신이 경계를 섰다.'),
    ],
    { requires: (s) => s.survivors.some((sv) => sv.alive) },
  ),
  ev(
    'e120',
    21,
    29,
    '동료의 편지',
    '동료가 몰래 써 둔 편지를 발견했다. 혹시 모를 순간을 위한 것 같다.',
    'story',
    [
      c('readLetter120', '조용히 읽어 본다', [mental(-5), survivorTrust(10)], '그 마음이 절절히 느껴졌다.'),
      c('putBack120', '제자리에 둔다', [mental(3)], '못 본 척 제자리에 돌려놓았다.'),
    ],
    { fixed: true, requires: (s) => s.survivors.some((sv) => sv.alive) },
  ),
  ev(
    'e121',
    21,
    29,
    '다른 생각',
    '동료 한 명이 혼자서라도 다른 길을 찾아보겠다고 말한다.',
    'story',
    [
      c('persuade121', '설득한다', [survivorTrust(15)], '끝내 마음을 돌렸다.'),
      c('letGo121', '뜻을 존중한다', [survivorLeave(), mental(-5)], '말리지 않기로 했다.'),
    ],
    { requires: (s) => s.survivors.some((sv) => sv.alive) },
  ),
  ev(
    'e122',
    11,
    ENDLESS_DAY_MAX,
    '고마움의 표시',
    '동료가 작은 선물 같은 것을 건넨다. 별것 아니지만 마음이 담겨 있다.',
    'story',
    [
      c('acceptGift122', '고맙게 받는다', [survivorTrust(10), mental(3)], '마음이 따뜻해졌다.'),
      c('shrugGift122', '대수롭지 않게 넘긴다', [survivorTrust(-3)], '동료가 살짝 서운한 기색을 보였다.'),
    ],
    { repeatable: true, cooldownDays: 5, requires: (s) => s.survivors.some((sv) => sv.alive) },
  ),
  ev(
    'e123',
    16,
    25,
    '동료의 가족 이야기',
    '동료가 처음으로 가족 이야기를 꺼낸다.',
    'story',
    [
      c('listen123', '끝까지 들어 준다', [survivorTrust(15), mental(-3)], '무거운 이야기였지만 끝까지 들었다.'),
      c('changeSubject123', '화제를 돌린다', [survivorTrust(-5)], '애써 다른 이야기로 넘어갔다.'),
    ],
    { fixed: true, requires: (s) => s.survivors.some((sv) => sv.alive) },
  ),
  ev(
    'e124',
    21,
    29,
    '책임을 나누다',
    '위험한 일을 누가 맡을지 정해야 한다.',
    'danger',
    [
      c('selfRisk124', '자신이 나선다', [hp(-10)], '스스로 위험을 감수했다.'),
      c('shareRisk124', '동료와 함께 나선다', [hp(-5), survivorHp(-5), survivorTrust(10)], '함께 위험을 나눴다.'),
    ],
    { requires: (s) => s.survivors.some((sv) => sv.alive) },
  ),
  ev(
    'e125',
    16,
    29,
    '동료의 생일',
    '동료가 오늘이 자신의 생일이라고 말한다. 이런 곳에서도 그런 게 기억나는구나 싶다.',
    'rare',
    [
      c('celebrate125', '작게라도 축하해 준다', [item('can', -1), survivorTrust(15), mental(5)], '없는 살림에도 작은 축하를 건넸다.', { item: 'can' }),
      c('justSay125', '말로만 축하한다', [survivorTrust(5)], '따뜻한 말 한마디를 건넸다.'),
    ],
    { requires: (s) => s.survivors.some((sv) => sv.alive) },
  ),
]

// ============================== 추가분 3 : 후반부(21일 이후) 보강 ==============================
// 21~29일 구간과 엔드리스 구간의 밀도가 얇았던 걸 보완하는 이벤트들.
const LATE_GAME_EXTRA: GameEvent[] = [
  ev(
    'e126',
    21,
    ENDLESS_DAY_MAX,
    '장기전의 무게',
    '버텨야 할 날이 언제 끝날지 모른다는 사실이 무겁게 짓누른다.',
    'danger',
    [
      c('shoulderOn126', '그래도 견딘다', [mental(-5)], '무거운 마음을 안고 하루를 버텼다.'),
      c('lean126', '동료에게 기댄다', [mental(5), survivorTrust(5)], '옆에 누군가 있다는 사실에 위안을 얻었다.', { survivor: true }),
    ],
    { repeatable: true, cooldownDays: 4 },
  ),
  ev(
    'e127',
    21,
    ENDLESS_DAY_MAX,
    '잊혀진 통신',
    '라디오 채널 사이에서 아주 희미한 신호가 잡힌다.',
    'story',
    [
      roll('tuneIn127', '주파수를 맞춰 본다', 50, [info(10)], '단편적이지만 쓸모 있는 정보를 얻었다.', [], '잡음만 가득했다.', { item: 'radio' }),
      c('skip127', '그냥 넘긴다', [], '신경 쓰지 않기로 했다.'),
    ],
    { repeatable: true, cooldownDays: 4 },
  ),
  ev(
    'e128',
    21,
    ENDLESS_DAY_MAX,
    '재고 정리',
    '가진 것들을 다시 정리해 본다.',
    'resource',
    [
      c('organize128', '꼼꼼히 정리한다', [shelter(5)], '정리하고 나니 공간이 한결 넓어졌다.'),
      c('skipOrganize128', '대충 넘긴다', [], '딱히 달라진 건 없었다.'),
    ],
    { repeatable: true, cooldownDays: 4 },
  ),
  ev(
    'e129',
    21,
    ENDLESS_DAY_MAX,
    '새로운 습격 루트',
    '이전과 다른 방향에서 인기척이 느껴진다.',
    'danger',
    [
      c('reinforce129', '그쪽을 보강한다', [shelter(-5)], '급한 대로 막았지만 자재가 부족했다.'),
      roll('watch129', '일단 지켜본다', 60, [], '다행히 별일 없었다.', [shelter(-15)], '미처 막지 못한 곳이 뚫렸다.'),
    ],
    { repeatable: true, cooldownDays: 3 },
  ),
  ev(
    'e130',
    26,
    ENDLESS_DAY_MAX,
    '정적',
    '오늘따라 대피소 안이 유난히 조용하다.',
    'story',
    [
      c('embraceQuiet130', '그 정적을 즐긴다', [mental(5)], '오랜만에 마음이 편안했다.'),
      c('uneasyQuiet130', '괜히 불안하다', [mental(-3)], '조용함이 오히려 불안하게 느껴졌다.'),
    ],
    { repeatable: true, cooldownDays: 3 },
  ),
  ev(
    'e131',
    21,
    ENDLESS_DAY_MAX,
    '오래된 습관',
    '매일 같은 시간에 눈이 떠지는 게 이제는 습관이 됐다.',
    'survival',
    [
      c('keepRoutine131', '정해진 대로 움직인다', [mental(3)], '익숙한 하루의 흐름이 마음을 다잡아 줬다.'),
      c('breakRoutine131', '오늘은 다르게 보낸다', [hp(5), mental(-3)], '평소와 다르게 몸을 쉬게 했다.'),
    ],
    { repeatable: true, cooldownDays: 3 },
  ),
  ev(
    'e132',
    30,
    ENDLESS_DAY_MAX,
    '서른 번째 아침',
    '서른 번째 아침이 밝았다. 원래대로라면 오늘이 마지막이었을 것이다.',
    'story',
    [
      c('reflect132', '그 사실을 곱씹는다', [mental(5)], '정해진 날을 넘어섰다는 사실이 새삼스럽다.'),
      c('moveOn132', '신경 쓰지 않는다', [], '오늘도 다를 것 없는 하루로 여기기로 했다.'),
    ],
    { fixed: true },
  ),
  ev(
    'e133',
    30,
    ENDLESS_DAY_MAX,
    '잊지 않은 이유',
    '왜 이렇게까지 버티고 있는지, 스스로에게 물어본다.',
    'story',
    [
      c('remember133', '이유를 떠올린다', [mental(10)], '분명한 이유가 있었다는 걸 다시 확인했다.'),
      c('noAnswer133', '답을 찾지 못한다', [mental(-5)], '뚜렷한 답이 떠오르지 않았다.'),
    ],
    { fixed: true },
  ),
]

// ============================== 추가분 4 : 1회성 소모 장비 ==============================
// 소지 공간 제한이 없어진 대신, 도구 몇 가지는 특정 이벤트에서 한 번 크게
// 쓰고 나면 그 자리에서 사라진다 (item(id, -1)). 다른 이벤트/탐색에서
// 이 도구를 요구하는 경우엔 영향이 없고, 새로 하나를 더 챙겨야 다시 쓸 수 있다.
const CONSUMABLE_TOOL_EXTRA: GameEvent[] = [
  ev(
    'e134',
    1,
    ENDLESS_DAY_MAX,
    '굳게 닫힌 문',
    '안쪽에 뭔가 있을 것 같은 문이 굳게 닫혀 있다.',
    'danger',
    [
      c('breakDoor134', '도끼로 부순다', [item('axe', -1), food(2), water(2)], '도끼로 몇 번이고 내리쳐 부쉈다. 날이 완전히 무뎌져 더는 쓸 수 없다. 안에서 식량과 물을 찾았다.', { item: 'axe' }),
      c('leaveDoor134', '포기한다', [], '무리하지 않고 돌아섰다.'),
    ],
    { repeatable: true, cooldownDays: 4 },
  ),
  ev(
    'e135',
    6,
    ENDLESS_DAY_MAX,
    '고장 난 배관',
    '벽 안쪽 배관이 완전히 망가졌다.',
    'resource',
    [
      c('fixPipe135', '공구함을 탈탈 털어 고친다', [item('toolbox', -1), shelter(15)], '가진 공구를 다 써서 뜯어고쳤다. 공구함 안은 이제 텅 비었다.', { item: 'toolbox' }),
      c('leavePipe135', '그냥 둔다', [shelter(-5)], '손대지 않았다. 조금씩 더 상했다.'),
    ],
    { repeatable: true, cooldownDays: 4 },
  ),
  ev(
    'e136',
    6,
    ENDLESS_DAY_MAX,
    '오염된 저수조',
    '커다란 저수조에 물이 남아 있지만, 색이 탁하다.',
    'resource',
    [
      c('purify136', '정수 필터로 끝까지 거른다', [item('filter', -1), water(5)], '필터가 완전히 막힐 때까지 거르고 또 걸렀다. 대신 꽤 많은 물을 확보했다.', { item: 'filter' }),
      c('skipTank136', '위험을 무릅쓰지 않는다', [], '손대지 않기로 했다.'),
    ],
    { repeatable: true, cooldownDays: 4 },
  ),
  ev(
    'e137',
    6,
    ENDLESS_DAY_MAX,
    '밤하늘의 신호',
    '멀리서 규칙적으로 반짝이는 빛이 보인다.',
    'story',
    [
      c('scanSky137', '망원경으로 끝까지 관찰한다', [item('binoculars', -1), info(15)], '오랫동안 눈에 대고 있었더니 렌즈에 금이 갔다. 대신 값진 정보를 얻었다.', { item: 'binoculars' }),
      c('skipSky137', '대충 보고 만다', [info(3)], '대충 훑어보고 말았다.'),
    ],
    { repeatable: true, cooldownDays: 5 },
  ),
  ev(
    'e138',
    1,
    ENDLESS_DAY_MAX,
    '손전등 배터리 방전',
    '어두운 구석을 뒤지려면 불빛이 필요하다.',
    'danger',
    [
      c('useLight138', '손전등을 밝혀 끝까지 뒤진다', [item('flashlight', -1), item('medicine', 1)], '구석구석 비추다 결국 전구가 나갔다. 대신 의약품을 찾았다.', { item: 'flashlight' }),
      c('skipLight138', '어둠 속에서 대충 찾는다', [], '대충 손으로 더듬어 찾다 포기했다.'),
    ],
    { repeatable: true, cooldownDays: 4 },
  ),
  ev(
    'e139',
    6,
    ENDLESS_DAY_MAX,
    '깜빡이는 손전등',
    '밖을 향해 불빛을 비추면 누군가 알아챌지도 모른다.',
    'story',
    [
      c('signalHelp139', '손전등으로 계속 신호를 보낸다', [item('flashlight', -1), info(10)], '전구가 나갈 때까지 신호를 보냈다. 누군가 반응한 것 같다.', { item: 'flashlight' }),
      c('skipSignal139', '신호를 보내지 않는다', [], '괜히 위치를 드러내고 싶지 않았다.'),
    ],
    { repeatable: true, cooldownDays: 5 },
  ),
  ev(
    'e140',
    6,
    ENDLESS_DAY_MAX,
    '지도의 빈 구석',
    '지도 귀퉁이에 손으로 그려 둔 표시가 있다.',
    'resource',
    [
      c('markMap140', '표시를 따라가 본다', [item('map', -1), food(3), water(3)], '표시를 따라가 봤다. 지도는 접었다 폈다 하다 다 해졌다. 대신 숨겨진 비축분을 찾았다.', { item: 'map' }),
      c('skipMark140', '무시한다', [], '대수롭지 않게 여기고 넘겼다.'),
    ],
    { repeatable: true, cooldownDays: 5 },
  ),
  ev(
    'e141',
    11,
    ENDLESS_DAY_MAX,
    '지도에 없는 길',
    '지도를 보니 지름길이 있는 것 같다.',
    'danger',
    [
      roll('shortcut141', '지도를 보며 지름길로 간다', 60, [item('map', -1), info(10)], '지름길을 발견했다. 지도는 접었다 폈다 하다 다 해져 버렸다.', [item('map', -1), hp(-10)], '지도를 믿고 나섰다가 길을 잃고 다쳤다. 지도는 이미 걸레가 됐다.', { item: 'map' }),
      c('safeRoute141', '안전한 길로 돌아간다', [], '시간이 걸려도 아는 길로만 다녔다.'),
    ],
    { repeatable: true, cooldownDays: 5 },
  ),
  ev(
    'e142',
    6,
    ENDLESS_DAY_MAX,
    '무전기 잡음 속 목소리',
    '무전기 너머로 끊어질 듯한 목소리가 들린다.',
    'story',
    [
      c('pushThrough142', '배터리를 다 써서 매달린다', [item('walkie', -1), info(15)], '배터리가 다 닳을 때까지 매달렸다. 끊어질 듯한 목소리에서 값진 정보를 얻었다.', { item: 'walkie' }),
      c('giveUpRadio142', '포기한다', [], '잡음만 가득해 포기했다.'),
    ],
    { repeatable: true, cooldownDays: 5 },
  ),
  ev(
    'e143',
    16,
    ENDLESS_DAY_MAX,
    '무전기로 도움 요청',
    '무전기로 구조를 요청해 볼까 고민한다.',
    'danger',
    [
      roll('callHelp143', '무전기로 구조를 요청한다', 50, [item('walkie', -1), shelter(10)], '누군가 응답해 도움을 줬다. 무전기는 그 후로 먹통이 됐다.', [item('walkie', -1)], '응답이 없었다. 무전기만 못 쓰게 됐다.', { item: 'walkie' }),
      c('stayQuiet143', '조용히 있는다', [], '괜히 위치를 알리지 않기로 했다.'),
    ],
    { repeatable: true, cooldownDays: 5 },
  ),
  ev(
    'e144',
    1,
    ENDLESS_DAY_MAX,
    '배터리 방전 직전',
    '전자기기 배터리가 거의 다 됐다.',
    'survival',
    [
      c('useBattery144', '배터리를 갈아 끼운다', [item('battery', -1), power(5)], '배터리를 새로 넣으니 다시 돌아갔다.', { item: 'battery' }),
      c('skipBattery144', '일단 놔둔다', [power(-5)], '전력이 조금 더 줄었다.'),
    ],
    { repeatable: true, cooldownDays: 4 },
  ),
  ev(
    'e145',
    16,
    ENDLESS_DAY_MAX,
    '마지막 배터리',
    '남은 배터리가 하나뿐이다. 지금 쓸지 아껴 둘지 정해야 한다.',
    'resource',
    [
      c('emergencyPower145', '비상 전력으로 돌린다', [item('battery', -1), shelter(10)], '남은 배터리를 아낌없이 썼다. 덕분에 급한 곳을 고쳤다.', { item: 'battery' }),
      c('saveBattery145', '아껴 둔다', [], '다음을 위해 아끼기로 했다.'),
    ],
    { repeatable: true, cooldownDays: 5 },
  ),
  ev(
    'e146',
    1,
    ENDLESS_DAY_MAX,
    '얇은 담요',
    '밤이 유난히 춥다.',
    'survival',
    [
      c('shareBlanket146', '담요를 찢어 나눠 쓴다', [item('blanket', -1), mental(5)], '담요를 찢어 여럿이 나눠 덮었다. 하나였던 온기가 흩어졌다.', { item: 'blanket' }),
      c('keepBlanket146', '혼자 덮는다', [], '그냥 혼자 덮기로 했다.'),
    ],
    { repeatable: true, cooldownDays: 4 },
  ),
  ev(
    'e147',
    16,
    ENDLESS_DAY_MAX,
    '해진 담요',
    '상처를 감쌀 게 마땅치 않다.',
    'survival',
    [
      c('patchUp147', '담요를 뜯어 상처를 감싼다', [item('blanket', -1), hp(10)], '담요 천을 찢어 상처에 둘렀다. 더는 덮을 수 없게 됐다.', { item: 'blanket' }),
      c('bearWound147', '다른 방법을 찾는다', [hp(-5)], '마땅한 게 없어 그냥 참았다.'),
    ],
    { repeatable: true, cooldownDays: 5 },
  ),
  ev(
    'e148',
    6,
    ENDLESS_DAY_MAX,
    '찢어진 틈새',
    '벽 틈으로 오염된 공기가 새어 들어온다.',
    'danger',
    [
      c('sealGap148', '마스크를 뜯어 틈을 막는다', [item('mask', -1), contamination(-10)], '마스크 천으로 틈을 틀어막았다. 이제 마스크는 없다.', { item: 'mask' }),
      c('ignoreGap148', '그냥 둔다', [contamination(10)], '딱히 손쓰지 못했다.'),
    ],
    { repeatable: true, cooldownDays: 4 },
  ),
  ev(
    'e149',
    16,
    ENDLESS_DAY_MAX,
    '오염된 공기',
    '이 구간을 지나려면 매캐한 공기를 뚫어야 한다.',
    'danger',
    [
      roll('pushThroughFumes149', '마스크를 쓰고 뚫고 나간다', 70, [item('mask', -1), info(10)], '마스크 덕에 버텼지만 필터가 완전히 막혔다.', [item('mask', -1), hp(-10)], '그래도 매캐한 기운에 다쳤다. 마스크는 못 쓰게 됐다.', { item: 'mask' }),
      c('retreatFumes149', '물러난다', [], '위험을 무릅쓰지 않았다.'),
    ],
    { repeatable: true, cooldownDays: 5 },
  ),
  ev(
    'e150',
    1,
    ENDLESS_DAY_MAX,
    '젖은 성냥',
    '몸이 얼어붙을 만큼 춥다.',
    'survival',
    [
      c('dryFire150', '성냥을 아낌없이 써 불을 피운다', [item('matches', -1), mental(5), hp(5)], '몇 개비를 연달아 그어 겨우 불을 피웠다.', { item: 'matches' }),
      c('coldNight150', '불 없이 견딘다', [hp(-5)], '불 없이 밤을 견뎠다.'),
    ],
    { repeatable: true, cooldownDays: 4 },
  ),
  ev(
    'e151',
    16,
    ENDLESS_DAY_MAX,
    '연기 신호',
    '연기를 피우면 멀리서도 보일 것 같다.',
    'story',
    [
      c('smokeSignal151', '성냥으로 연기 신호를 피운다', [item('matches', -1), info(10)], '남은 성냥을 다 태워 신호를 피웠다. 누군가 알아챈 것 같다.', { item: 'matches' }),
      c('noSignal151', '신호를 보내지 않는다', [], '괜히 위치를 드러내고 싶지 않았다.'),
    ],
    { repeatable: true, cooldownDays: 5 },
  ),
  ev(
    'e152',
    6,
    ENDLESS_DAY_MAX,
    '낚싯대가 부러지다',
    '큰 놈이 걸린 것 같다. 무리해서라도 끌어올릴지 고민된다.',
    'resource',
    [
      roll('bigCatch152', '무리해서라도 큰 걸 노린다', 55, [item('fishingRod', -1), food(5)], '무리한 만큼 큰 걸 낚았다. 그 대신 낚싯대가 부러졌다.', [item('fishingRod', -1)], '낚싯대만 부러지고 허탕을 쳤다.', { item: 'fishingRod' }),
      c('safeFish152', '무리하지 않는다', [food(1)], '욕심내지 않고 적당히 낚았다.'),
    ],
    { repeatable: true, cooldownDays: 5 },
  ),
  ev(
    'e153',
    1,
    ENDLESS_DAY_MAX,
    '칼을 벼리다',
    '가진 칼이 무뎌졌다.',
    'survival',
    [
      c('sharpenAndUse153', '날이 다 닳도록 손질에 쓴다', [item('knife', -1), food(2)], '날이 다 닳도록 손질에 썼다. 더는 쓸 수 없게 됐지만 식재료를 오래 두고 먹을 수 있게 됐다.', { item: 'knife' }),
      c('keepKnife153', '아껴 둔다', [], '다음을 위해 아끼기로 했다.'),
    ],
    { repeatable: true, cooldownDays: 4 },
  ),
  ev(
    'e154',
    11,
    ENDLESS_DAY_MAX,
    '칼로 맞서다',
    '뭔가가 대피소 가까이 다가온다.',
    'danger',
    [
      roll('fightBack154', '칼을 들고 맞선다', 65, [item('knife', -1), shelter(-5)], '가까스로 쫓아냈다. 칼날이 부러져 더는 못 쓴다.', [item('knife', -1), hp(-15)], '맞서다 다쳤다. 칼마저 부러졌다.', { item: 'knife' }),
      c('hideAway154', '숨어서 지나가길 기다린다', [mental(-3)], '숨죽이고 지나가길 기다렸다.'),
    ],
    { repeatable: true, cooldownDays: 4 },
  ),
  ev(
    'e155',
    6,
    ENDLESS_DAY_MAX,
    '다 읽은 책',
    '몇 번이고 읽어 이제 다 외울 지경이다.',
    'story',
    [
      c('tearForFire155', '책을 찢어 불쏘시개로 쓴다', [item('book', -1), hp(5)], '몇 번이고 읽은 책이었지만, 찢어서 불을 피웠다.', { item: 'book' }),
      c('keepBook155', '그냥 둔다', [mental(3)], '그래도 곁에 두기로 했다.'),
    ],
    { repeatable: true, cooldownDays: 5 },
  ),
  ev(
    'e156',
    16,
    ENDLESS_DAY_MAX,
    '빛바랜 사진',
    '오래 품고 있던 사진을 꺼내 본다.',
    'story',
    [
      c('letGoPhoto156', '사진을 태우며 작별한다', [item('photo', -1), mental(10)], '오래 품고 있던 사진을 태우며 마음을 정리했다.', { item: 'photo' }),
      c('keepPhoto156', '품에 넣어 둔다', [], '그래도 계속 지니고 있기로 했다.'),
    ],
    { repeatable: true, cooldownDays: 5 },
  ),
  ev(
    'e157',
    6,
    ENDLESS_DAY_MAX,
    '씨앗을 심다',
    '남는 자리에 씨앗을 심어 볼까 한다.',
    'resource',
    [
      c('plantSeed157', '씨앗을 심는다', [item('seed', -1), flag('gardenPlanted'), food(2)], '씨앗을 심었다. 당장은 크지 않지만 흙 사이로 싹이 보인다.', { item: 'seed' }),
      c('skipPlant157', '심지 않는다', [], '아직은 때가 아니라고 여겼다.'),
    ],
    { fixed: true },
  ),
  ev(
    'e158',
    11,
    ENDLESS_DAY_MAX,
    '텃밭의 첫 수확',
    '심어 뒀던 씨앗이 자라 작은 수확을 맺었다.',
    'resource',
    [c('harvest158', '수확한다', [food(3)], '작지만 확실한 수확이다.')],
    { repeatable: true, cooldownDays: 5, requires: (s) => s.flags.gardenPlanted === true },
  ),
]

export const ALL_EVENTS: GameEvent[] = [
  ...DAY_1_5,
  ...DAY_6_10,
  ...DAY_11_15,
  ...DAY_16_20,
  ...DAY_21_25,
  ...DAY_26_29,
  ...SURVIVAL_EXTRA,
  ...COMPANION_EXTRA,
  ...LATE_GAME_EXTRA,
  ...CONSUMABLE_TOOL_EXTRA,
]

export const EVENT_MAP: Record<string, GameEvent> = Object.fromEntries(ALL_EVENTS.map((e) => [e.id, e]))
